"use client";

import { ArrowRight, Brain, Layers, RefreshCw, ChevronDown, Sparkles } from "lucide-react";
import { signIn } from "next-auth/react";
import { motion, AnimatePresence } from "framer-motion";
import { useState, useEffect } from "react";
import { Highlight, themes } from "prism-react-renderer";

const luauTheme = {
  ...themes.vsDark,
  plain: {
    color: "#e2e8f0",
    backgroundColor: "transparent",
  },
  styles: [
    ...themes.vsDark.styles,
    {
      types: ["keyword", "operator"],
      style: {
        color: "#ccff00",
        fontWeight: "600",
      },
    },
    {
      types: ["string", "char"],
      style: {
        color: "#10b981",
      },
    },
    {
      types: ["function"],
      style: {
        color: "#60a5fa",
      },
    },
    {
      types: ["comment"],
      style: {
        color: "#4b5563",
        fontStyle: "italic",
      },
    },
  ],
};

/* ─── FAQ data ─── */
const FAQ_ITEMS = [
  {
    question: "Is Apple Juice affiliated with Roblox Corporation?",
    answer:
      "No. Apple Juice is an independent, open-source project. It is not affiliated with, endorsed by, or sponsored by Roblox Corporation. Sign-in is performed through the official Roblox OAuth 2.0 API — a publicly available developer program — so the authorization screen you see is hosted and operated by Roblox, not us.",
  },
  {
    question: "Is Apple Juice free to use?",
    answer:
      "Yes. Apple Juice is free and open-source (MIT License). You only pay for AI inference — either through your own OpenAI or Google AI Studio API key, or by using the platform's shared credit pool.",
  },
  {
    question: "What data does Roblox share when I sign in?",
    answer:
      "When you authorize Apple Juice via Roblox's OAuth 2.0 consent screen, Roblox shares only your User ID and public profile. We never receive your password, Robux balance, purchase history, or inventory. You can revoke access at any time from your Roblox account settings under \"Connected Apps\".",
  },
  {
    question: "Do you store my AI provider API keys?",
    answer:
      "Never. Your API keys are stored exclusively in your browser's localStorage. They are sent directly from your browser to OpenAI or Google AI Studio — our servers are not in that data path.",
  },
  {
    question: "How does the Studio plugin work?",
    answer:
      "You install a lightweight plugin from the Roblox Creator Store. It opens a persistent WebSocket connection to your dashboard using a short-lived pairing token. When the AI generates code, scripts are pushed through this connection and created in Studio automatically. The plugin operates only within the Studio sandbox and has no access to your account or game data outside the open place.",
  },
  {
    question: "Which AI models are supported?",
    answer:
      "OpenAI (GPT-4o, GPT-4.1) and Google Gemini (Gemini 2.5 Pro, Gemini 2.0 Flash). You can switch between them at any time in your dashboard settings.",
  },
  {
    question: "Does Apple Juice impose any rate limits on my API key?",
    answer:
      "No. When you supply your own API key, requests go directly from your browser to OpenAI or Google — Apple Juice adds zero throttling. You are limited only by your own account's rate tier (e.g. OpenAI Tier 1–5). If you use the shared credit pool, a per-user request limit applies to ensure fair access for all users.",
  },
];

/* ─── FAQ Accordion Item ─── */
function FaqItem({ question, answer }: { question: string; answer: string }) {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div className="border-b border-white/5">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex w-full items-center justify-between py-6 text-left group"
      >
        <span className="text-[15px] font-medium text-white/90 group-hover:text-white transition-colors">
          {question}
        </span>
        <motion.div animate={{ rotate: isOpen ? 180 : 0 }} transition={{ duration: 0.2 }}>
          <ChevronDown className="h-4 w-4 text-white/20 flex-shrink-0 ml-6" />
        </motion.div>
      </button>
      <motion.div
        initial={false}
        animate={{ height: isOpen ? "auto" : 0, opacity: isOpen ? 1 : 0 }}
        transition={{ duration: 0.25 }}
        className="overflow-hidden"
      >
        <p className="pb-6 text-sm leading-relaxed text-white/40 max-w-2xl">{answer}</p>
      </motion.div>
    </div>
  );
}

/* ─── Code snippets for terminal mockup ─── */
const MULTI_SCRIPTS = [
  { name: "WeaponSystem.lua", type: "ModuleScript", parent: "ReplicatedStorage", lines: 34, code: `-- 🟢 Generated by Apple Juice AI\nlocal ReplicatedStorage = game:GetService("ReplicatedStorage")\nlocal Players = game:GetService("Players")\n\nlocal WeaponSystem = {}\nWeaponSystem.__index = WeaponSystem\n\nfunction WeaponSystem.new(config)\n    local self = setmetatable({}, WeaponSystem)\n    self.Damage = config.Damage or 25\n    self.FireRate = config.FireRate or 0.15\n    self.MaxAmmo = config.MaxAmmo or 30\n    self.CurrentAmmo = self.MaxAmmo\n    return self\nend\n\nfunction WeaponSystem:Fire(origin, direction)\n    if self.CurrentAmmo <= 0 then return end\n    self.CurrentAmmo -= 1\n\n    local raycast = workspace:Raycast(origin, direction * 200)\n    if raycast and raycast.Instance then\n        local hit = raycast.Instance\n        local humanoid = hit.Parent:FindFirstChild("Humanoid")\n        if humanoid then\n            humanoid:TakeDamage(self.Damage)\n        end\n    end\nend\n\nreturn WeaponSystem` },
  { name: "WeaponHandler.lua", type: "LocalScript", parent: "StarterPlayerScripts", lines: 56, code: `-- 🟢 Generated by Apple Juice AI\nlocal Players = game:GetService("Players")\nlocal ReplicatedStorage = game:GetService("ReplicatedStorage")\nlocal UserInputService = game:GetService("UserInputService")\n\nlocal WeaponSystem = require(ReplicatedStorage:WaitForChild("WeaponSystem"))\nlocal player = Players.LocalPlayer\n\nlocal currentWeapon = WeaponSystem.new({\n    Damage = 30,\n    FireRate = 0.1,\n    MaxAmmo = 50\n})\n\nUserInputService.InputBegan:Connect(function(input, gameProcessed)\n    if gameProcessed then return end\n    \n    if input.UserInputType == Enum.UserInputType.MouseButton1 then\n        local mouseLocation = UserInputService:GetMouseLocation()\n        local ray = workspace.CurrentCamera:ViewportPointToRay(mouseLocation.X, mouseLocation.Y)\n        currentWeapon:Fire(ray.Origin, ray.Direction)\n    end\nend)` },
  { name: "DamageProcessor.lua", type: "Script", parent: "ServerScriptService", lines: 28, code: `-- 🟢 Generated by Apple Juice AI\nlocal ServerStorage = game:GetService("ServerStorage")\n\nlocal function processDamage(player, target, amount)\n    if not target or not target:IsA("Humanoid") then return end\n    \n    -- Perform server-side validation\n    if amount > 100 then\n        warn("Anti-cheat: Suspicious damage amount from " .. player.Name)\n        return\n    end\n    \n    target:TakeDamage(amount)\nend\n\n-- Bind to RemoteEvent\nlocal damageEvent = Instance.new("RemoteEvent")\ndamageEvent.Name = "DamageEvent"\ndamageEvent.Parent = game:GetService("ReplicatedStorage")\n\ndamageEvent.OnServerEvent:Connect(processDamage)` },
  { name: "AmmoUI.lua", type: "LocalScript", parent: "StarterGui", lines: 41, code: `-- 🟢 Generated by Apple Juice AI\nlocal Players = game:GetService("Players")\nlocal player = Players.LocalPlayer\nlocal playerGui = player:WaitForChild("PlayerGui")\n\nlocal screenGui = Instance.new("ScreenGui")\nscreenGui.Name = "AmmoDisplay"\nscreenGui.Parent = playerGui\n\nlocal ammoLabel = Instance.new("TextLabel")\nammoLabel.Size = UDim2.new(0, 200, 0, 50)\nammoLabel.Position = UDim2.new(1, -220, 1, -70)\nammoLabel.BackgroundTransparency = 0.5\nammoLabel.BackgroundColor3 = Color3.new(0, 0, 0)\nammoLabel.TextColor3 = Color3.new(1, 1, 1)\nammoLabel.TextScaled = true\nammoLabel.Font = Enum.Font.Code\nammoLabel.Parent = screenGui\n\nlocal function updateAmmoDisplay(current, max)\n    ammoLabel.Text = string.format("AMMO: %d / %d", current, max)\n    \n    if current <= max * 0.2 then\n        ammoLabel.TextColor3 = Color3.new(1, 0.2, 0.2)\n    else\n        ammoLabel.TextColor3 = Color3.new(1, 1, 1)\n    end\nend` },
];

/* ─── Main Landing Component ─── */
export function LandingContent({ session, avatarUrl: _avatarUrl }: { session: any; avatarUrl?: string }) {
  const [activeScriptIndex, setActiveScriptIndex] = useState(0);
  const [showAuthGuide, setShowAuthGuide] = useState(false);

  useEffect(() => {
    const interval = setInterval(() => {
      setActiveScriptIndex((prev) => (prev + 1) % MULTI_SCRIPTS.length);
    }, 4000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="min-h-screen bg-[#05050a] text-white selection:bg-blue-500 selection:text-white relative overflow-hidden">
      {/* ━━━ BACKGROUND GRID & AMBIENT GRADIENTS ━━━ */}
      <div className="absolute inset-0 bg-[url('https://res.cloudinary.com/dbuzl20eu/image/upload/v1691456100/grid_wqvngf.png')] bg-[length:32px_32px] opacity-[0.03] pointer-events-none z-0" />
      <div className="fixed top-[-20%] left-[-10%] w-[70vw] h-[70vw] rounded-full bg-blue-600/30 blur-[200px] pointer-events-none z-0 mix-blend-screen animate-blob-drift" />
      <div className="fixed bottom-[-20%] right-[-10%] w-[70vw] h-[70vw] rounded-full bg-red-600/30 blur-[200px] pointer-events-none z-0 mix-blend-screen animate-blob-drift-reverse" />

      {/* ━━━ NAVBAR ━━━ */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#05050a]/50 backdrop-blur-md border-b border-white/10">
        <div className="w-full max-w-[1600px] mx-auto px-6 lg:px-12 xl:px-20 h-20 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="h-10 w-10 rounded-xl bg-[#ccff00] flex items-center justify-center shadow-[0_0_15px_rgba(204,255,0,0.3)]">
              <svg viewBox="0 0 24 24" className="h-6 w-6 text-black" fill="currentColor">
                <path d="M5.2 6.5L7.5 3h9l2.3 3.5H5.2z" fillOpacity="0.8" />
                <path d="M5 8v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8H5z" />
                <path d="M15 3V1.5A1.5 1.5 0 0 0 13.5 0H12" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
                <path d="M14.5 14.5c0 1.5-1 2.5-2.5 2.5s-2.5-1-2.5-2.5 1-2.5 2.5-2.5c.3 0 .7.1 1 .2-.3.4-.3 1 0 1.4.3.4.9.4 1.3.1.1.2.2.5.2.8zM12.5 11c0-1-.8-1.5-1.5-1.5 0 1 .8 1.5 1.5 1.5z" fill="#ccff00" />
              </svg>
            </div>
            <span className="text-xl md:text-2xl font-black tracking-[0.2em] uppercase font-sans text-white drop-shadow-md">Apple Juice</span>
          </div>

          <div className="hidden md:flex items-center gap-10">
            <a href="#features" className="text-sm font-medium text-[#8a8f98] hover:text-white transition-colors">Features</a>
            <a href="#terminal" className="text-sm font-medium text-[#8a8f98] hover:text-white transition-colors">Demo</a>
            <a href="#faq" className="text-sm font-medium text-[#8a8f98] hover:text-white transition-colors">FAQ</a>
          </div>

          <button
            onClick={() => session ? window.location.href = "/dashboard" : setShowAuthGuide(true)}
            className="h-11 px-7 rounded-xl bg-white text-black text-base font-bold hover:bg-zinc-200 transition-colors shadow-[0_0_20px_rgba(255,255,255,0.2)] hover:shadow-[0_0_30px_rgba(255,255,255,0.4)]"
          >
            {session ? "Dashboard" : "Sign In"}
          </button>
        </div>
      </nav>

      {/* ━━━ HERO & TERMINAL ━━━ */}
      <section className="relative pt-40 lg:pt-52 pb-32 px-6 lg:px-12 xl:px-20 z-10">
        {/* Deep background glow */}
        <div className="absolute top-[-10%] lg:top-0 left-1/2 lg:left-[20%] -translate-x-1/2 w-[600px] h-[600px] bg-blue-600/15 rounded-full blur-[150px] pointer-events-none animate-blob-drift" />

        <div className="w-full max-w-[1600px] mx-auto relative z-10 flex flex-col lg:flex-row items-center justify-between gap-16 xl:gap-24">
          
          {/* Hero Content */}
          <div className="flex-1 text-center lg:text-left flex flex-col items-center lg:items-start">
            {/* Eyebrow */}
            <div className="inline-flex items-center px-4 py-2 rounded-full border border-white/10 bg-[#0a0a0a] mb-8 lg:mb-10 shadow-[0_0_20px_rgba(204,255,0,0.05)] animate-fade-up">
              <Sparkles className="h-3.5 w-3.5 text-[#ccff00] mr-2" />
              <span className="text-[10px] tracking-[0.2em] uppercase font-bold text-[#8a8f98]">
                Open Source · Free Forever · Roblox OAuth 2.0
              </span>
            </div>

            {/* Headline */}
            <h1 className="text-6xl sm:text-7xl lg:text-[4.5rem] xl:text-[5rem] font-extrabold tracking-[-0.04em] leading-[1.05] text-white mb-6 lg:mb-8 animate-fade-up-delay">
              The AI Code Studio <br />
              for <span className="font-serif italic font-medium text-[#ccff00]">Roblox</span> Developers.
            </h1>

            {/* Subtext */}
            <p className="max-w-xl lg:max-w-lg text-lg sm:text-xl text-[#8a8f98] leading-relaxed mb-10 lg:mb-12 mx-auto lg:mx-0 animate-fade-up-delay-2">
              Describe what you want to build. Apple Juice generates production-ready Luau code and injects it directly into Roblox Studio — no copy-pasting, no context switching.
            </p>

            {/* Lemonade-style Buttons */}
            <div className="flex flex-col sm:flex-row items-center gap-5 w-full sm:w-auto animate-fade-up-delay-2">
              {/* Primary Shine Button */}
              <button
                onClick={() => session ? window.location.href = "/dashboard" : signIn("", { callbackUrl: "/dashboard" })}
                className="relative inline-flex h-14 w-full sm:w-auto items-center justify-center px-10 py-2 font-bold text-white transition-all rounded-xl bg-[#101317] border border-white/10 hover:border-white/20 hover:shadow-[0_0_30px_rgba(204,255,0,0.1)] group overflow-hidden"
                style={{
                  backgroundImage: 'linear-gradient(110deg, #101317 40%, rgba(204, 255, 0, 0.15) 50%, #101317 60%)',
                  backgroundSize: '200% auto',
                }}
              >
                <div className="absolute inset-0 w-full h-full animate-shine bg-[linear-gradient(110deg,transparent_20%,rgba(204,255,0,0.1)_30%,rgba(204,255,0,0.1)_40%,transparent_50%)] bg-[length:200%_auto]" />
                <span className="relative z-10 flex items-center gap-2">
                  Start Prototyping
                  <ArrowRight className="h-4 w-4 group-hover:translate-x-1 transition-transform" />
                </span>
              </button>

              {/* Secondary Link Button */}
              <button className="h-14 px-8 text-sm font-semibold text-[#8a8f98] hover:text-white transition-colors flex items-center justify-center gap-2 w-full sm:w-auto">
                Watch Demo <span className="text-lg leading-none">→</span>
              </button>
            </div>
          </div>

          {/* Terminal Mockup */}
          <div id="terminal" className="flex-1 w-full max-w-2xl lg:max-w-none">
            {/* macOS-style window chrome */}
            <div className="rounded-2xl border border-white/10 bg-[#0a0a0a] shadow-2xl shadow-black/50 overflow-hidden relative z-10">
              {/* Title bar */}
              <div className="flex items-center gap-2 px-4 py-3 border-b border-white/10 bg-[#0a0a0a]">
                <div className="flex gap-1.5">
                  <div className="h-3 w-3 rounded-full bg-[#ff5f57]" />
                  <div className="h-3 w-3 rounded-full bg-[#febc2e]" />
                  <div className="h-3 w-3 rounded-full bg-[#28c840]" />
                </div>
                <span className="ml-3 text-[11px] text-[#8a8f98] font-mono">Apple Juice — AI Output</span>
              </div>

              {/* Content */}
              <div className="flex flex-col xl:flex-row">
                {/* Code panel */}
                <div className="flex-1 p-5 border-b xl:border-b-0 xl:border-r border-white/10 overflow-hidden min-h-[400px]">
                  <AnimatePresence mode="wait">
                    <motion.pre
                      key={activeScriptIndex}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -10 }}
                      transition={{ duration: 0.3 }}
                      className="font-mono text-[12px] xl:text-[13px] leading-[1.8]"
                    >
                      <Highlight
                        theme={luauTheme}
                        code={MULTI_SCRIPTS[activeScriptIndex].code}
                        language="lua"
                      >
                        {({ tokens, getTokenProps }) => (
                          <code>
                            {tokens.map((line, i) => (
                              <div key={i}>
                                {line.map((token, key) => (
                                  <span key={key} {...getTokenProps({ token })} />
                                ))}
                              </div>
                            ))}
                          </code>
                        )}
                      </Highlight>
                    </motion.pre>
                  </AnimatePresence>
                </div>

                {/* File list panel */}
                <div className="w-full xl:w-64 p-5 space-y-3 bg-[#050505] flex-shrink-0">
                  <p className="text-[10px] tracking-[0.2em] uppercase font-bold text-[#8a8f98] mb-5">
                    Generated Files
                  </p>
                  {MULTI_SCRIPTS.map((s, i) => (
                    <div
                      key={i}
                      onClick={() => setActiveScriptIndex(i)}
                      className={`flex items-center justify-between p-3.5 rounded-xl border transition-all duration-300 cursor-pointer ${
                        activeScriptIndex === i 
                          ? 'bg-white/10 border-white/30 shadow-[0_0_15px_rgba(255,255,255,0.1)]' 
                          : 'bg-[#0a0a0a] border-white/10 hover:border-white/20'
                      }`}
                    >
                      <div className="truncate pr-2">
                        <p className={`text-[13px] font-semibold truncate ${activeScriptIndex === i ? 'text-white' : 'text-white/70'}`}>{s.name}</p>
                        <p className="text-[11px] text-[#8a8f98] mt-1 truncate">
                          {s.type} · {s.parent}
                        </p>
                      </div>
                      <span className="text-[11px] text-white/20 font-mono flex-shrink-0">{s.lines}L</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ━━━ FEATURES ━━━ */}
      <section id="features" className="px-6 pb-40">
        <div className="max-w-[1100px] mx-auto">
          {/* Section label */}
          <div className="text-center mb-20">
            <p className="text-[10px] tracking-[0.2em] uppercase font-bold text-[#ccff00] mb-4">
              Why Apple Juice
            </p>
            <h2 className="text-4xl sm:text-5xl font-extrabold tracking-tight text-white">
              Engineering-Grade. Zero Friction.
            </h2>
          </div>

          {/* Feature cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {/* Card 1 */}
            <div className="group p-8 rounded-2xl bg-[#0a0a0a] border border-white/10 hover:border-white/20 transition-all duration-300 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full blur-[50px] group-hover:bg-white/10 transition-colors" />
              <div className="h-12 w-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 relative z-10">
                <Brain className="h-6 w-6 text-white/80" />
              </div>
              <h3 className="text-xl font-bold mb-3 text-white">Chain-of-Thought Reasoning</h3>
              <p className="text-[#8a8f98] leading-relaxed">
                Enable Thinking Mode and the model reasons through your feature step-by-step before writing a single line of code. Complex systems get a thorough first-principles analysis, resulting in smarter, more robust Luau that requires fewer manual fixes.
              </p>
            </div>

            {/* Card 2 */}
            <div className="group p-8 rounded-2xl bg-[#0a0a0a] border border-white/10 hover:border-white/20 transition-all duration-300 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full blur-[50px] group-hover:bg-white/10 transition-colors" />
              <div className="h-12 w-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 relative z-10">
                <Layers className="h-6 w-6 text-white/80" />
              </div>
              <h3 className="text-xl font-bold mb-3 text-white">Multi-File Architecture</h3>
              <p className="text-[#8a8f98] leading-relaxed">
                Generate entire interconnected systems in one shot. Apple Juice can orchestrate ModuleScripts, ServerScripts, and LocalScripts simultaneously — wiring them together with remote events and placing them into the correct Explorer locations instantly.
              </p>
            </div>

            {/* Card 3 */}
            <div className="group p-8 rounded-2xl bg-[#0a0a0a] border border-white/10 hover:border-white/20 transition-all duration-300 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full blur-[50px] group-hover:bg-white/10 transition-colors" />
              <div className="h-12 w-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 relative z-10">
                <RefreshCw className="h-6 w-6 text-white/80" />
              </div>
              <h3 className="text-xl font-bold mb-3 text-white">Self-Healing Debug Loop</h3>
              <p className="text-[#8a8f98] leading-relaxed">
                Apple Juice streams your Roblox console output in real time. When a runtime error or exception is detected, the AI automatically analyzes the stack trace and directly proposes a targeted fix, cutting your debugging time down to zero.
              </p>
            </div>

            {/* Card 4 */}
            <div className="group p-8 rounded-2xl bg-[#0a0a0a] border border-white/10 hover:border-white/20 transition-all duration-300 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-blue-500/5 rounded-full blur-[50px] group-hover:bg-blue-500/10 transition-colors" />
              <div className="h-12 w-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 relative z-10">
                <svg viewBox="0 0 24 24" className="h-6 w-6 text-white/80" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>
              </div>
              <h3 className="text-xl font-bold mb-3 text-white">Zero-Latency Studio Sync</h3>
              <p className="text-[#8a8f98] leading-relaxed">
                A highly optimized Studio plugin maintains a persistent, lightning-fast WebSocket connection to your web session. The code materializes in your Explorer tree the exact millisecond the language model finishes generation — completely eliminating clipboard copying.
              </p>
            </div>

            {/* Card 5 */}
            <div className="group p-8 rounded-2xl bg-[#0a0a0a] border border-white/10 hover:border-white/20 transition-all duration-300 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-red-500/5 rounded-full blur-[50px] group-hover:bg-red-500/10 transition-colors" />
              <div className="h-12 w-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 relative z-10">
                <svg viewBox="0 0 24 24" className="h-6 w-6 text-white/80" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/></svg>
              </div>
              <h3 className="text-xl font-bold mb-3 text-white">Context-Aware Generation</h3>
              <p className="text-[#8a8f98] leading-relaxed">
                Upload existing scripts directly or let Apple Juice dynamically read your current project tree. The model uses your entire existing codebase as context, ensuring that generated components match your naming conventions, stylistic patterns, and game architecture.
              </p>
            </div>

            {/* Card 6 */}
            <div className="group p-8 rounded-2xl bg-[#0a0a0a] border border-white/10 hover:border-white/20 transition-all duration-300 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-purple-500/5 rounded-full blur-[50px] group-hover:bg-purple-500/10 transition-colors" />
              <div className="h-12 w-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 relative z-10">
                <svg viewBox="0 0 24 24" className="h-6 w-6 text-white/80" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
              </div>
              <h3 className="text-xl font-bold mb-3 text-white">Secure by Architecture</h3>
              <p className="text-[#8a8f98] leading-relaxed">
                Your AI provider API keys are stored exclusively in your browser's local memory and interact directly with OpenAI or Google. Our servers act only as a transparent proxy. Furthermore, authentication leverages the official, robust Roblox OAuth 2.0 API.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ━━━ FAQ ━━━ */}
      <section id="faq" className="px-6 pb-40">
        <div className="max-w-[700px] mx-auto">
          <div className="text-center mb-16">
            <p className="text-[10px] tracking-[0.2em] uppercase font-bold text-[#8a8f98] mb-4">
              FAQ
            </p>
            <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight">
              Frequently Asked Questions
            </h2>
          </div>

          <div className="rounded-2xl border border-white/10 bg-[#0a0a0a] px-8">
            {FAQ_ITEMS.map((item, i) => (
              <FaqItem key={i} question={item.question} answer={item.answer} />
            ))}
          </div>
        </div>
      </section>

      {/* ━━━ BOTTOM CTA ━━━ */}
      <section className="px-6 pb-40">
        <div className="max-w-[800px] mx-auto text-center p-16 rounded-[2rem] bg-[#0a0a0a] border border-white/10 relative overflow-hidden">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[400px] h-[400px] bg-red-600/10 rounded-full blur-[100px] pointer-events-none" />
          
          <div className="relative z-10">
            <h2 className="text-4xl sm:text-5xl font-extrabold tracking-tight mb-6">
              Ship your next feature tonight.
            </h2>
            <p className="text-lg text-[#8a8f98] mb-10 max-w-xl mx-auto">
              Join Roblox developers who go from idea to working Luau code in minutes. <br/> <strong className="text-white mt-2 block">Ready to ditch the credits? Bring your own API key and get zero limits.</strong>
            </p>
            
            <button
              onClick={() => session ? window.location.href = "/dashboard" : signIn("", { callbackUrl: "/dashboard" })}
              className="relative inline-flex h-14 items-center justify-center px-10 py-2 font-bold text-white transition-all rounded-xl bg-[#101317] border border-white/10 hover:border-white/20 hover:shadow-[0_0_30px_rgba(204,255,0,0.1)] group overflow-hidden"
              style={{
                backgroundImage: 'linear-gradient(110deg, #101317 40%, rgba(204, 255, 0, 0.15) 50%, #101317 60%)',
                backgroundSize: '200% auto',
              }}
            >
              <div className="absolute inset-0 w-full h-full animate-shine bg-[linear-gradient(110deg,transparent_20%,rgba(204,255,0,0.1)_30%,rgba(204,255,0,0.1)_40%,transparent_50%)] bg-[length:200%_auto]" />
              <span className="relative z-10 flex items-center gap-2">
                Start Building for Free
                <ArrowRight className="h-4 w-4 group-hover:translate-x-1 transition-transform" />
              </span>
            </button>
          </div>
        </div>
      </section>

      {/* ━━━ FOOTER ━━━ */}
      <footer className="border-t border-white/10 px-6 py-12 bg-[#090a0d]">
        <div className="max-w-[1200px] mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            <div className="h-7 w-7 rounded-lg bg-[#ccff00] flex items-center justify-center">
              <svg viewBox="0 0 24 24" className="h-4 w-4 text-black" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                <path d="M10 2v3" />
                <rect x="5" y="5" width="14" height="17" rx="3" />
                <path d="M5 10h14" />
              </svg>
            </div>
            <span className="text-lg font-black tracking-[0.1em] font-serif italic text-[#8a8f98]">Apple Juice</span>
          </div>
          
          <div className="flex items-center gap-6">
            <a href="#" className="text-sm text-[#8a8f98] hover:text-white transition-colors">Twitter</a>
            <a href="#" className="text-sm text-[#8a8f98] hover:text-white transition-colors">GitHub</a>
            <a href="#" className="text-sm text-[#8a8f98] hover:text-white transition-colors">Discord</a>
            <a href="mailto:info@apple-juice.online" className="text-sm text-[#8a8f98] hover:text-white transition-colors">Support</a>
            <a href="/tos" className="text-sm text-[#8a8f98] hover:text-white transition-colors">Terms</a>
            <a href="/privacy" className="text-sm text-[#8a8f98] hover:text-white transition-colors">Privacy</a>
            <a href="/eula" className="text-sm text-[#8a8f98] hover:text-white transition-colors">EULA</a>
          </div>

          <p className="text-[11px] text-[#8a8f98] text-center md:text-right max-w-xs">
            Independent open-source project. Not affiliated with or endorsed by Roblox Corporation. Roblox® is a trademark of Roblox Corporation.
          </p>
        </div>
      </footer>

      {/* ━━━ OAUTH GUIDE MODAL ━━━ */}
      {showAuthGuide && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
          <div className="w-full max-w-2xl bg-[#111113] border border-white/10 rounded-2xl shadow-2xl overflow-hidden flex flex-col relative animate-in zoom-in-95 duration-200">
            {/* Header */}
            <div className="h-16 flex items-center px-8 border-b border-white/5 bg-[#0a0a0c]">
              <span className="font-bold text-lg tracking-wide text-white">How we authenticate you</span>
            </div>
            
            {/* Body */}
            <div className="p-8 sm:p-10 overflow-y-auto max-h-[75vh]">
              <p className="text-[#8a8f98] text-base leading-relaxed mb-8">
                Clicking &ldquo;Continue&rdquo; will open the <strong className="text-white">official Roblox authorization screen</strong> — hosted at roblox.com and operated entirely by Roblox. Here is exactly what is shared and how it is used:
              </p>
              
              <div className="space-y-6">
                {/* Section 1 */}
                <div className="bg-[#1a1a1c] border border-white/5 rounded-xl p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="h-8 w-8 rounded-full bg-blue-500/10 flex items-center justify-center border border-blue-500/20">
                      <span className="text-blue-400 font-bold">1</span>
                    </div>
                    <h3 className="text-lg font-semibold text-white">Your Roblox Profile (via OAuth 2.0)</h3>
                  </div>
                  <p className="text-sm text-[#8a8f98] mb-4">
                    Roblox will ask you to grant Apple Juice access to your <strong className="text-white">User ID</strong> and <strong className="text-white">public profile</strong>, as shown on Roblox&apos;s consent screen.
                  </p>
                  <ul className="text-sm text-[#8a8f98] space-y-2 list-disc pl-5">
                    <li>We use your User ID to identify your dashboard session and display your avatar.</li>
                    <li><strong className="text-[#ccff00]">We NEVER receive your password.</strong></li>
                    <li><strong className="text-[#ccff00]">We NEVER receive your Robux balance, purchase history, or inventory.</strong></li>
                    <li>You can revoke access at any time via your Roblox account settings under &ldquo;Connected Apps&rdquo;.</li>
                  </ul>
                  {/* Why OAuth? callout */}
                  <div className="mt-4 flex items-start gap-2.5 p-3 rounded-lg bg-white/5 border border-white/10">
                    <span className="text-[#ccff00] text-sm font-bold flex-shrink-0 mt-0.5">?</span>
                    <p className="text-xs text-[#8a8f98] leading-relaxed">
                      <strong className="text-white">Why OAuth 2.0?</strong>{" "}
                      OAuth ensures we never touch your password and allows you to revoke Apple Juice&apos;s access instantly from your Roblox Security settings — no contacting us required.
                    </p>
                  </div>
                </div>

                {/* Section 2 */}
                <div className="bg-[#1a1a1c] border border-white/5 rounded-xl p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="h-8 w-8 rounded-full bg-[#ccff00]/10 flex items-center justify-center border border-[#ccff00]/20">
                      <span className="text-[#ccff00] font-bold">2</span>
                    </div>
                    <h3 className="text-lg font-semibold text-white">The Studio Plugin (separate install)</h3>
                  </div>
                  <p className="text-sm text-[#8a8f98] mb-4">
                    After signing in, you can install the Apple Juice plugin from the Roblox Creator Store. Here is exactly what it does — and what it does not:
                  </p>
                  <ul className="text-sm text-[#8a8f98] space-y-3">
                    <li className="flex items-start gap-2">
                       <span className="text-yellow-500 mt-0.5 flex-shrink-0">●</span> 
                       <span><strong className="text-white">Write Scripts (Medium Risk):</strong> Creates or overwrites scripts in your place <em>only</em> when you explicitly trigger a generation.</span>
                    </li>
                    <li className="flex items-start gap-2">
                       <span className="text-green-500 mt-0.5 flex-shrink-0">●</span> 
                       <span><strong className="text-white">Read Explorer Tree (Low Risk):</strong> Reads your folder structure (e.g. <code className="text-white/60 bg-white/5 px-1 rounded">ReplicatedStorage</code>) so the AI places files correctly.</span>
                    </li>
                    <li className="flex items-start gap-2">
                       <span className="text-white/30 mt-0.5 flex-shrink-0">●</span> 
                       <span><strong className="text-white">No account access:</strong> The plugin cannot read your Roblox credentials, Robux, or any data outside the open Studio session.</span>
                    </li>
                  </ul>
                </div>

                {/* Step 3 — Next Steps */}
                <div className="bg-[#1a1a1c] border border-white/5 rounded-xl p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="h-8 w-8 rounded-full bg-white/5 flex items-center justify-center border border-white/10">
                      <span className="text-white/60 font-bold">3</span>
                    </div>
                    <h3 className="text-lg font-semibold text-white">What happens after you sign in</h3>
                  </div>
                  <p className="text-sm text-[#8a8f98] mb-4">
                    Once authorized, follow these three steps to go live:
                  </p>
                  <ol className="text-sm text-[#8a8f98] space-y-3">
                    <li className="flex items-start gap-3">
                      <span className="h-5 w-5 rounded-full bg-[#ccff00]/10 border border-[#ccff00]/30 text-[#ccff00] text-[11px] font-bold flex items-center justify-center flex-shrink-0 mt-0.5">1</span>
                      <span><strong className="text-white">Open Roblox Studio</strong> and install the Apple Juice plugin from the Creator Store.</span>
                    </li>
                    <li className="flex items-start gap-3">
                      <span className="h-5 w-5 rounded-full bg-[#ccff00]/10 border border-[#ccff00]/30 text-[#ccff00] text-[11px] font-bold flex items-center justify-center flex-shrink-0 mt-0.5">2</span>
                      <span><strong className="text-white">Copy your Pairing Token</strong> from the dashboard and paste it into the plugin to link your session.</span>
                    </li>
                    <li className="flex items-start gap-3">
                      <span className="h-5 w-5 rounded-full bg-[#ccff00]/10 border border-[#ccff00]/30 text-[#ccff00] text-[11px] font-bold flex items-center justify-center flex-shrink-0 mt-0.5">3</span>
                      <span><strong className="text-white">Click &ldquo;Fetch Context&rdquo;</strong> in the plugin to sync your Explorer tree. You&apos;re ready to generate.</span>
                    </li>
                  </ol>
                </div>
              </div>
            </div>
            
            {/* Footer */}
            <div className="px-6 py-5 border-t border-white/5 bg-[#0a0a0c] flex flex-col sm:flex-row items-center justify-between gap-4">
              <p className="text-[11px] text-[#8a8f98] text-center sm:text-left">
                Apple Juice is an independent project. Not affiliated with Roblox Corporation.
              </p>
              <div className="flex items-center gap-3">
                <button 
                  onClick={() => setShowAuthGuide(false)}
                  className="px-6 py-2.5 rounded-lg border border-white/10 text-white hover:bg-white/5 text-sm font-medium transition-colors"
                >
                  Cancel
                </button>
                <button 
                  onClick={() => signIn("roblox", { callbackUrl: "/dashboard" })}
                  className="px-8 py-2.5 rounded-lg bg-white text-black hover:bg-zinc-200 text-sm font-bold transition-colors shadow-[0_0_15px_rgba(255,255,255,0.2)]"
                >
                  Continue to Roblox Sign-In →
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
