"use client";

import { ArrowRight, Brain, Layers, RefreshCw, ChevronDown, Sparkles } from "lucide-react";
import { signIn } from "next-auth/react";
import { motion } from "framer-motion";
import { useState } from "react";

/* ─── FAQ data ─── */
const FAQ_ITEMS = [
  {
    question: "Is Apple Juice free to use?",
    answer:
      "Yes, Apple Juice is 100% free and open-source. You only pay for your own API usage through OpenAI or Google AI Studio.",
  },
  {
    question: "How does it connect to Roblox Studio?",
    answer:
      "You run a lightweight plugin inside Studio that auto-pairs with your dashboard session. When you generate a script, it instantly materializes in your Explorer tree.",
  },
  {
    question: "Do you store my API keys?",
    answer:
      "Never. Your API keys live exclusively in your browser's localStorage. They are sent directly to the AI providers — our servers never see them.",
  },
  {
    question: "Which AI models are supported?",
    answer:
      "OpenAI (GPT-4o, GPT-4.1) and Google Gemini models. You can switch between them instantly in your dashboard settings.",
  },
];

/* ─── FAQ Accordion Item ─── */
function FaqItem({ question, answer }: { question: string; answer: string }) {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div className="border-b border-white/5">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex w-full items-center justify-between py-6 text-left group"
      >
        <span className="text-[15px] font-medium text-white/90 group-hover:text-white transition-colors">
          {question}
        </span>
        <motion.div animate={{ rotate: isOpen ? 180 : 0 }} transition={{ duration: 0.2 }}>
          <ChevronDown className="h-4 w-4 text-white/20 flex-shrink-0 ml-6" />
        </motion.div>
      </button>
      <motion.div
        initial={false}
        animate={{ height: isOpen ? "auto" : 0, opacity: isOpen ? 1 : 0 }}
        transition={{ duration: 0.25 }}
        className="overflow-hidden"
      >
        <p className="pb-6 text-sm leading-relaxed text-white/40 max-w-2xl">{answer}</p>
      </motion.div>
    </div>
  );
}

/* ─── Code snippets for terminal mockup ─── */
const TERMINAL_CODE = `-- 🟢 Generated by Apple Juice AI
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")

local WeaponSystem = {}
WeaponSystem.__index = WeaponSystem

function WeaponSystem.new(config)
    local self = setmetatable({}, WeaponSystem)
    self.Damage = config.Damage or 25
    self.FireRate = config.FireRate or 0.15
    self.MaxAmmo = config.MaxAmmo or 30
    self.CurrentAmmo = self.MaxAmmo
    return self
end

function WeaponSystem:Fire(origin, direction)
    if self.CurrentAmmo <= 0 then return end
    self.CurrentAmmo -= 1

    local raycast = workspace:Raycast(origin, direction * 200)
    if raycast and raycast.Instance then
        local hit = raycast.Instance
        local humanoid = hit.Parent:FindFirstChild("Humanoid")
        if humanoid then
            humanoid:TakeDamage(self.Damage)
        end
    end
end

return WeaponSystem`;

const MULTI_SCRIPTS = [
  { name: "WeaponSystem.lua", type: "ModuleScript", parent: "ReplicatedStorage", lines: 34 },
  { name: "WeaponHandler.lua", type: "LocalScript", parent: "StarterPlayerScripts", lines: 56 },
  { name: "DamageProcessor.lua", type: "Script", parent: "ServerScriptService", lines: 28 },
  { name: "AmmoUI.lua", type: "LocalScript", parent: "StarterGui", lines: 41 },
];

/* ─── Main Landing Component ─── */
export function LandingContent({ session, avatarUrl: _avatarUrl }: { session: any; avatarUrl?: string }) {
  return (
    <div className="min-h-screen bg-[#090a0d] text-white selection:bg-[#ccff00] selection:text-black">
      {/* ━━━ BACKGROUND GRID ━━━ */}
      <div className="absolute inset-0 bg-[url('https://res.cloudinary.com/dbuzl20eu/image/upload/v1691456100/grid_wqvngf.png')] bg-[length:32px_32px] opacity-[0.03] pointer-events-none" />

      {/* ━━━ NAVBAR ━━━ */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#090a0d]/50 backdrop-blur-md border-b border-white/10">
        <div className="max-w-[1200px] mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-6 w-6 rounded bg-[#ccff00] flex items-center justify-center">
              <svg viewBox="0 0 24 24" className="h-3.5 w-3.5 text-black" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                <path d="M10 2v3" />
                <rect x="5" y="5" width="14" height="17" rx="3" />
                <path d="M5 10h14" />
              </svg>
            </div>
            <span className="text-[17px] font-bold tracking-tight text-white">Apple Juice</span>
          </div>

          <div className="hidden md:flex items-center gap-10">
            <a href="#features" className="text-sm font-medium text-[#8a8f98] hover:text-white transition-colors">Features</a>
            <a href="#terminal" className="text-sm font-medium text-[#8a8f98] hover:text-white transition-colors">Demo</a>
            <a href="#faq" className="text-sm font-medium text-[#8a8f98] hover:text-white transition-colors">FAQ</a>
          </div>

          <button
            onClick={() => signIn("", { callbackUrl: "/dashboard" })}
            className="h-9 px-5 rounded-lg bg-white text-black text-sm font-semibold hover:bg-zinc-200 transition-colors"
          >
            {session ? "Dashboard" : "Sign In"}
          </button>
        </div>
      </nav>

      {/* ━━━ HERO & TERMINAL ━━━ */}
      <section className="relative pt-32 lg:pt-44 pb-32 px-6">
        {/* Deep background glow */}
        <div className="absolute top-[-10%] lg:top-0 left-1/2 lg:left-[20%] -translate-x-1/2 w-[600px] h-[600px] bg-[#ccff00]/10 rounded-full blur-[150px] pointer-events-none" />

        <div className="max-w-[1200px] mx-auto relative z-10 flex flex-col lg:flex-row items-center gap-16 lg:gap-12">
          
          {/* Hero Content */}
          <div className="flex-1 text-center lg:text-left flex flex-col items-center lg:items-start">
            {/* Eyebrow */}
            <div className="inline-flex items-center px-4 py-2 rounded-full border border-white/10 bg-[#0a0a0a] mb-8 lg:mb-10 shadow-[0_0_20px_rgba(204,255,0,0.05)]">
              <Sparkles className="h-3.5 w-3.5 text-[#ccff00] mr-2" />
              <span className="text-[10px] tracking-[0.2em] uppercase font-bold text-[#8a8f98]">
                Open Source · Free Forever
              </span>
            </div>

            {/* Headline */}
            <h1 className="text-6xl sm:text-7xl lg:text-[4.5rem] xl:text-[5rem] font-extrabold tracking-[-0.04em] leading-[1.05] text-white mb-6 lg:mb-8">
              The first AI Code <br />
              Tool for <span className="text-[#ccff00]">Roblox</span>
            </h1>

            {/* Subtext */}
            <p className="max-w-xl lg:max-w-lg text-lg sm:text-xl text-[#8a8f98] leading-relaxed mb-10 lg:mb-12 mx-auto lg:mx-0">
              Describe what you want to build. Get production-ready Luau code injected directly into Roblox Studio — in seconds.
            </p>

            {/* Lemonade-style Buttons */}
            <div className="flex flex-col sm:flex-row items-center gap-5 w-full sm:w-auto">
              {/* Primary Shine Button */}
              <button
                onClick={() => signIn("", { callbackUrl: "/dashboard" })}
                className="relative inline-flex h-14 w-full sm:w-auto items-center justify-center px-10 py-2 font-bold text-white transition-all rounded-xl bg-[#101317] border border-white/10 hover:border-white/20 hover:shadow-[0_0_30px_rgba(204,255,0,0.1)] group overflow-hidden"
                style={{
                  backgroundImage: 'linear-gradient(110deg, #101317 40%, rgba(204, 255, 0, 0.15) 50%, #101317 60%)',
                  backgroundSize: '200% auto',
                }}
              >
                <div className="absolute inset-0 w-full h-full animate-shine bg-[linear-gradient(110deg,transparent_20%,rgba(204,255,0,0.1)_30%,rgba(204,255,0,0.1)_40%,transparent_50%)] bg-[length:200%_auto]" />
                <span className="relative z-10 flex items-center gap-2">
                  Start Prototyping
                  <ArrowRight className="h-4 w-4 group-hover:translate-x-1 transition-transform" />
                </span>
              </button>

              {/* Secondary Link Button */}
              <button className="h-14 px-8 text-sm font-semibold text-[#8a8f98] hover:text-white transition-colors flex items-center justify-center gap-2 w-full sm:w-auto">
                Watch Demo <span className="text-lg leading-none">→</span>
              </button>
            </div>
          </div>

          {/* Terminal Mockup */}
          <div id="terminal" className="flex-1 w-full max-w-2xl lg:max-w-none">
            {/* macOS-style window chrome */}
            <div className="rounded-2xl border border-white/10 bg-[#0a0a0a] shadow-2xl shadow-black/50 overflow-hidden relative z-10">
              {/* Title bar */}
              <div className="flex items-center gap-2 px-4 py-3 border-b border-white/10 bg-[#0a0a0a]">
                <div className="flex gap-1.5">
                  <div className="h-3 w-3 rounded-full bg-[#ff5f57]" />
                  <div className="h-3 w-3 rounded-full bg-[#febc2e]" />
                  <div className="h-3 w-3 rounded-full bg-[#28c840]" />
                </div>
                <span className="ml-3 text-[11px] text-[#8a8f98] font-mono">Apple Juice — AI Output</span>
              </div>

              {/* Content */}
              <div className="flex flex-col xl:flex-row">
                {/* Code panel */}
                <div className="flex-1 p-5 border-b xl:border-b-0 xl:border-r border-white/10 overflow-x-auto">
                  <pre className="font-mono text-[12px] xl:text-[13px] leading-[1.8] text-[#a1a1aa]">
                    <code>{TERMINAL_CODE}</code>
                  </pre>
                </div>

                {/* File list panel */}
                <div className="w-full xl:w-64 p-5 space-y-3 bg-[#050505] flex-shrink-0">
                  <p className="text-[10px] tracking-[0.2em] uppercase font-bold text-[#8a8f98] mb-5">
                    Generated Files
                  </p>
                  {MULTI_SCRIPTS.map((s, i) => (
                    <div
                      key={i}
                      className="flex items-center justify-between p-3.5 rounded-xl bg-[#0a0a0a] border border-white/10 hover:border-white/20 transition-colors duration-200"
                    >
                      <div className="truncate pr-2">
                        <p className="text-[13px] font-semibold text-white/90 truncate">{s.name}</p>
                        <p className="text-[11px] text-[#8a8f98] mt-1 truncate">
                          {s.type} · {s.parent}
                        </p>
                      </div>
                      <span className="text-[11px] text-white/20 font-mono flex-shrink-0">{s.lines}L</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ━━━ FEATURES ━━━ */}
      <section id="features" className="px-6 pb-40">
        <div className="max-w-[1100px] mx-auto">
          {/* Section label */}
          <div className="text-center mb-20">
            <p className="text-[10px] tracking-[0.2em] uppercase font-bold text-[#ccff00] mb-4">
              Why Apple Juice
            </p>
            <h2 className="text-4xl sm:text-5xl font-extrabold tracking-tight text-white">
              Built Different
            </h2>
          </div>

          {/* Feature cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Card 1 */}
            <div className="group p-8 rounded-2xl bg-[#0a0a0a] border border-white/10 hover:border-white/20 transition-all duration-300 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full blur-[50px] group-hover:bg-white/10 transition-colors" />
              <div className="h-12 w-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 relative z-10">
                <Brain className="h-6 w-6 text-white/80" />
              </div>
              <h3 className="text-xl font-bold mb-3 text-white">Chain-of-Thought</h3>
              <p className="text-[#8a8f98] leading-relaxed">
                Toggle Thinking Mode to let the AI reason step-by-step before writing code. Architect-level prompts generate smarter, more robust Luau scripts.
              </p>
            </div>

            {/* Card 2 */}
            <div className="group p-8 rounded-2xl bg-[#0a0a0a] border border-white/10 hover:border-white/20 transition-all duration-300 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full blur-[50px] group-hover:bg-white/10 transition-colors" />
              <div className="h-12 w-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 relative z-10">
                <Layers className="h-6 w-6 text-white/80" />
              </div>
              <h3 className="text-xl font-bold mb-3 text-white">Multi-File Architecture</h3>
              <p className="text-[#8a8f98] leading-relaxed">
                Generate entire systems — ModuleScripts, ServerScripts, LocalScripts — all wired together and injected into your Explorer tree at once.
              </p>
            </div>

            {/* Card 3 */}
            <div className="group p-8 rounded-2xl bg-[#0a0a0a] border border-white/10 hover:border-white/20 transition-all duration-300 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full blur-[50px] group-hover:bg-white/10 transition-colors" />
              <div className="h-12 w-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 relative z-10">
                <RefreshCw className="h-6 w-6 text-white/80" />
              </div>
              <h3 className="text-xl font-bold mb-3 text-white">Self-Healing Loop</h3>
              <p className="text-[#8a8f98] leading-relaxed">
                Apple Juice reads your Roblox console output. When an error is detected, it automatically suggests a fix — or repairs the script for you.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ━━━ FAQ ━━━ */}
      <section id="faq" className="px-6 pb-40">
        <div className="max-w-[700px] mx-auto">
          <div className="text-center mb-16">
            <p className="text-[10px] tracking-[0.2em] uppercase font-bold text-[#8a8f98] mb-4">
              FAQ
            </p>
            <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight">
              Frequently Asked Questions
            </h2>
          </div>

          <div className="rounded-2xl border border-white/10 bg-[#0a0a0a] px-8">
            {FAQ_ITEMS.map((item, i) => (
              <FaqItem key={i} question={item.question} answer={item.answer} />
            ))}
          </div>
        </div>
      </section>

      {/* ━━━ BOTTOM CTA ━━━ */}
      <section className="px-6 pb-40">
        <div className="max-w-[800px] mx-auto text-center p-16 rounded-[2rem] bg-[#0a0a0a] border border-white/10 relative overflow-hidden">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[400px] h-[400px] bg-[#ccff00]/5 rounded-full blur-[100px] pointer-events-none" />
          
          <div className="relative z-10">
            <h2 className="text-4xl sm:text-5xl font-extrabold tracking-tight mb-6">
              Ready to build faster?
            </h2>
            <p className="text-lg text-[#8a8f98] mb-10 max-w-lg mx-auto">
              Join developers who are shipping Roblox games faster with AI-powered code generation.
            </p>
            
            <button
              onClick={() => signIn("", { callbackUrl: "/dashboard" })}
              className="relative inline-flex h-14 items-center justify-center px-10 py-2 font-bold text-white transition-all rounded-xl bg-[#101317] border border-white/10 hover:border-white/20 hover:shadow-[0_0_30px_rgba(204,255,0,0.1)] group overflow-hidden"
              style={{
                backgroundImage: 'linear-gradient(110deg, #101317 40%, rgba(204, 255, 0, 0.15) 50%, #101317 60%)',
                backgroundSize: '200% auto',
              }}
            >
              <div className="absolute inset-0 w-full h-full animate-shine bg-[linear-gradient(110deg,transparent_20%,rgba(204,255,0,0.1)_30%,rgba(204,255,0,0.1)_40%,transparent_50%)] bg-[length:200%_auto]" />
              <span className="relative z-10 flex items-center gap-2">
                Start Building Now
                <ArrowRight className="h-4 w-4 group-hover:translate-x-1 transition-transform" />
              </span>
            </button>
          </div>
        </div>
      </section>

      {/* ━━━ FOOTER ━━━ */}
      <footer className="border-t border-white/10 px-6 py-12 bg-[#090a0d]">
        <div className="max-w-[1200px] mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-3">
            <div className="h-5 w-5 rounded bg-[#ccff00] flex items-center justify-center">
              <svg viewBox="0 0 24 24" className="h-2.5 w-2.5 text-black" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                <path d="M10 2v3" />
                <rect x="5" y="5" width="14" height="17" rx="3" />
                <path d="M5 10h14" />
              </svg>
            </div>
            <span className="text-sm font-bold text-[#8a8f98]">Apple Juice</span>
          </div>
          
          <div className="flex items-center gap-6">
            <a href="#" className="text-sm text-[#8a8f98] hover:text-white transition-colors">Twitter</a>
            <a href="#" className="text-sm text-[#8a8f98] hover:text-white transition-colors">GitHub</a>
            <a href="#" className="text-sm text-[#8a8f98] hover:text-white transition-colors">Discord</a>
          </div>

          <p className="text-[11px] text-[#8a8f98]">
            Open source · Not affiliated with Roblox Corporation
          </p>
        </div>
      </footer>
    </div>
  );
}
