"use client";

import { ArrowRight, ChevronDown, Sparkles } from "lucide-react";
import { signIn } from "next-auth/react";
import { motion, AnimatePresence } from "framer-motion";
import { useState, useEffect } from "react";
import { Highlight, themes, type PrismTheme } from "prism-react-renderer";

const luauTheme: PrismTheme = {
  ...themes.vsDark,
  plain: {
    color: "#e2e8f0",
    backgroundColor: "transparent",
  },
  styles: [
    ...themes.vsDark.styles,
    {
      types: ["keyword", "operator"],
      style: {
        color: "#ccff00",
        fontWeight: "bold",
      },
    },
    {
      types: ["string", "char"],
      style: {
        color: "#10b981",
      },
    },
    {
      types: ["function"],
      style: {
        color: "#60a5fa",
      },
    },
    {
      types: ["comment"],
      style: {
        color: "#4b5563",
        fontStyle: "italic",
      },
    },
  ],
};

/* ─── FAQ data ─── */
const FAQ_ITEMS = [
  {
    question: "Is Apple Juice affiliated with Roblox Corporation?",
    answer:
      "No. Apple Juice is an independent, open-source project. It is not affiliated with, endorsed by, or sponsored by Roblox Corporation. Sign-in is performed through the official Roblox OAuth 2.0 API — a publicly available developer program — so the authorization screen you see is hosted and operated by Roblox, not us.",
  },
  {
    question: "Is Apple Juice free to use?",
    answer:
      "Yes. Apple Juice is free and open-source (MIT License). You only pay for AI inference — either through your own OpenAI or Google AI Studio API key, or by using the platform's shared credit pool.",
  },
  {
    question: "What data do you receive when I sign in?",
    answer:
      "If you authorize via Roblox, we receive only your User ID and public profile. If you use Google, we receive your email and basic profile. We NEVER receive your password, Robux balance, purchase history, or inventory. You can revoke access at any time from your account settings.",
  },
  {
    question: "Do you store my AI provider API keys?",
    answer:
      "Never. Your API keys are stored exclusively in your browser's localStorage. They are sent directly from your browser to OpenAI or Google AI Studio — our servers are not in that data path.",
  },
  {
    question: "How does the Studio plugin work?",
    answer:
      "You install a lightweight plugin from the Roblox Creator Store. It opens a persistent WebSocket connection to your dashboard using a short-lived pairing token. When the AI generates code, scripts are pushed through this connection and created in Studio automatically. The plugin operates only within the Studio sandbox and has no access to your account or game data outside the open place.",
  },
  {
    question: "Which AI models are supported?",
    answer:
      "OpenAI (GPT-4o, GPT-4.1) and Google Gemini (Gemini 2.5 Pro, Gemini 2.0 Flash). You can switch between them at any time in your dashboard settings.",
  },
  {
    question: "Does Apple Juice impose any rate limits on my API key?",
    answer:
      "No. When you supply your own API key, requests go directly from your browser to OpenAI or Google — Apple Juice adds zero throttling. You are limited only by your own account's rate tier (e.g. OpenAI Tier 1–5). If you use the shared credit pool, a per-user request limit applies to ensure fair access for all users.",
  },
];

/* ─── FAQ Accordion Item ─── */
function FaqItem({ question, answer }: { question: string; answer: string }) {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div className="border-b border-white/5">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex w-full items-center justify-between py-4 text-left group"
      >
        <span className="text-sm font-medium text-white/90 group-hover:text-white transition-colors">
          {question}
        </span>
        <motion.div animate={{ rotate: isOpen ? 180 : 0 }} transition={{ duration: 0.2 }}>
          <ChevronDown className="h-4 w-4 text-white/20 flex-shrink-0 ml-6" />
        </motion.div>
      </button>
      <motion.div
        initial={false}
        animate={{ height: isOpen ? "auto" : 0, opacity: isOpen ? 1 : 0 }}
        transition={{ duration: 0.1 }}
        className="overflow-hidden"
      >
        <p className="pb-4 text-sm leading-relaxed text-white font-medium max-w-2xl">{answer}</p>
      </motion.div>
    </div>
  );
}

/* ─── Code snippets for terminal mockup ─── */
const MULTI_SCRIPTS = [
  { name: "WeaponSystem.lua", type: "ModuleScript", parent: "ReplicatedStorage", lines: 34, code: `-- 🟢 Generated by Apple Juice AI\nlocal ReplicatedStorage = game:GetService("ReplicatedStorage")\nlocal Players = game:GetService("Players")\n\nlocal WeaponSystem = {}\nWeaponSystem.__index = WeaponSystem\n\nfunction WeaponSystem.new(config)\n    local self = setmetatable({}, WeaponSystem)\n    self.Damage = config.Damage or 25\n    self.FireRate = config.FireRate or 0.15\n    self.MaxAmmo = config.MaxAmmo or 30\n    self.CurrentAmmo = self.MaxAmmo\n    return self\nend\n\nfunction WeaponSystem:Fire(origin, direction)\n    if self.CurrentAmmo <= 0 then return end\n    self.CurrentAmmo -= 1\n\n    local raycast = workspace:Raycast(origin, direction * 200)\n    if raycast and raycast.Instance then\n        local hit = raycast.Instance\n        local humanoid = hit.Parent:FindFirstChild("Humanoid")\n        if humanoid then\n            humanoid:TakeDamage(self.Damage)\n        end\n    end\nend\n\nreturn WeaponSystem` },
  { name: "WeaponHandler.lua", type: "LocalScript", parent: "StarterPlayerScripts", lines: 56, code: `-- 🟢 Generated by Apple Juice AI\nlocal Players = game:GetService("Players")\nlocal ReplicatedStorage = game:GetService("ReplicatedStorage")\nlocal UserInputService = game:GetService("UserInputService")\n\nlocal WeaponSystem = require(ReplicatedStorage:WaitForChild("WeaponSystem"))\nlocal player = Players.LocalPlayer\n\nlocal currentWeapon = WeaponSystem.new({\n    Damage = 30,\n    FireRate = 0.1,\n    MaxAmmo = 50\n})\n\nUserInputService.InputBegan:Connect(function(input, gameProcessed)\n    if gameProcessed then return end\n    \n    if input.UserInputType == Enum.UserInputType.MouseButton1 then\n        local mouseLocation = UserInputService:GetMouseLocation()\n        local ray = workspace.CurrentCamera:ViewportPointToRay(mouseLocation.X, mouseLocation.Y)\n        currentWeapon:Fire(ray.Origin, ray.Direction)\n    end\nend)` },
  { name: "DamageProcessor.lua", type: "Script", parent: "ServerScriptService", lines: 28, code: `-- 🟢 Generated by Apple Juice AI\nlocal ServerStorage = game:GetService("ServerStorage")\n\nlocal function processDamage(player, target, amount)\n    if not target or not target:IsA("Humanoid") then return end\n    \n    -- Perform server-side validation\n    if amount > 100 then\n        warn("Anti-cheat: Suspicious damage amount from " .. player.Name)\n        return\n    end\n    \n    target:TakeDamage(amount)\nend\n\n-- Bind to RemoteEvent\nlocal damageEvent = Instance.new("RemoteEvent")\ndamageEvent.Name = "DamageEvent"\ndamageEvent.Parent = game:GetService("ReplicatedStorage")\n\ndamageEvent.OnServerEvent:Connect(processDamage)` },
  { name: "AmmoUI.lua", type: "LocalScript", parent: "StarterGui", lines: 41, code: `-- 🟢 Generated by Apple Juice AI\nlocal Players = game:GetService("Players")\nlocal player = Players.LocalPlayer\nlocal playerGui = player:WaitForChild("PlayerGui")\n\nlocal screenGui = Instance.new("ScreenGui")\nscreenGui.Name = "AmmoDisplay"\nscreenGui.Parent = playerGui\n\nlocal ammoLabel = Instance.new("TextLabel")\nammoLabel.Size = UDim2.new(0, 200, 0, 50)\nammoLabel.Position = UDim2.new(1, -220, 1, -70)\nammoLabel.BackgroundTransparency = 0.5\nammoLabel.BackgroundColor3 = Color3.new(0, 0, 0)\nammoLabel.TextColor3 = Color3.new(1, 1, 1)\nammoLabel.TextScaled = true\nammoLabel.Font = Enum.Font.Code\nammoLabel.Parent = screenGui\n\nlocal function updateAmmoDisplay(current, max)\n    ammoLabel.Text = string.format("AMMO: %d / %d", current, max)\n    \n    if current <= max * 0.2 then\n        ammoLabel.TextColor3 = Color3.new(1, 0.2, 0.2)\n    else\n        ammoLabel.TextColor3 = Color3.new(1, 1, 1)\n    end\nend` },
];

/* ─── Main Landing Component ─── */
export function LandingContent({ session, avatarUrl: _avatarUrl }: { session: any; avatarUrl?: string }) {
  const [activeScriptIndex, setActiveScriptIndex] = useState(0);
  const [showAuthGuide, setShowAuthGuide] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [isRobux, setIsRobux] = useState(false);

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  useEffect(() => {
    const interval = setInterval(() => {
      setActiveScriptIndex((prev) => (prev + 1) % MULTI_SCRIPTS.length);
    }, 4000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="min-h-screen bg-[#060a12] text-white selection:bg-[#ccff00] selection:text-black relative font-sans">
      {/* ━━━ PREMIUM FIXED GRADIENT BACKGROUND ━━━ */}
      <div className="fixed inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(29,78,216,0.25),transparent_60%),radial-gradient(circle_at_15%_85%,rgba(37,99,235,0.15),transparent_50%),radial-gradient(circle_at_center,rgba(30,58,138,0.1),transparent_70%)] pointer-events-none z-0" />
      <div className="fixed inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:60px_60px] pointer-events-none z-0" />
      <div className="fixed inset-0 bg-gradient-to-b from-transparent via-[#080c16]/30 to-[#0a0e1a]/90 pointer-events-none z-0" />

      {/* ━━━ NAVBAR ━━━ */}
      <nav className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 flex justify-center ${scrolled ? "py-4 px-4 md:px-6" : "py-0 px-0"}`}>
        <div className={`w-full transition-all duration-300 flex items-center justify-between ${
          scrolled 
            ? "h-14 md:h-16 px-6 md:px-12 bg-[#0b101b]/90 backdrop-blur-xl border border-white/10 rounded-2xl shadow-2xl" 
            : "h-16 md:h-20 px-6 md:px-10 bg-transparent border border-transparent rounded-none"
        }`}>
          <div className="flex items-center gap-3 md:gap-4">
            <div className="h-8 w-8 md:h-9 md:w-9 rounded-xl bg-[#ccff00] flex items-center justify-center shadow-[0_0_25px_rgba(204,255,0,0.4)] flex-shrink-0">
              <svg viewBox="0 0 24 24" className="h-5 w-5 md:h-6 md:w-6 text-black" fill="currentColor">
                <path d="M5.2 6.5L7.5 3h9l2.3 3.5H5.2z" fillOpacity="0.8" />
                <path d="M5 8v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8H5z" />
                <path d="M15 3V1.5A1.5 1.5 0 0 0 13.5 0H12" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
                <path d="M14.5 14.5c0 1.5-1 2.5-2.5 2.5s-2.5-1-2.5-2.5 1-2.5 2.5-2.5c.3 0 .7.1 1 .2-.3.4-.3 1 0 1.4.3.4.9.4 1.3.1.1.2.2.5.2.8zM12.5 11c0-1-.8-1.5-1.5-1.5 0 1 .8 1.5 1.5 1.5z" fill="#ccff00" />
              </svg>
            </div>
            <span className="text-base md:text-xl font-black tracking-[0.15em] md:tracking-[0.25em] uppercase text-white">Apple Juice</span>
          </div>

          <div className={`hidden md:flex items-center transition-all duration-300 ${
            scrolled ? "gap-10 bg-black/60 border border-white/5 px-8 py-2.5 rounded-2xl shadow-inner" : "gap-12 px-0 py-0"
          }`}>
            <a href="#features" className="text-xs font-bold uppercase tracking-widest text-white hover:text-[#ccff00] transition-colors">Features</a>
            <a href="#terminal" className="text-xs font-bold uppercase tracking-widest text-white hover:text-[#ccff00] transition-colors">Demo</a>
            <a href="#faq" className="text-xs font-bold uppercase tracking-widest text-white hover:text-[#ccff00] transition-colors">FAQ</a>
          </div>

          <button
            onClick={() => session ? window.location.href = "/dashboard" : setShowAuthGuide(true)}
            className="h-10 md:h-11 px-5 md:px-8 rounded-xl bg-[#ccff00] text-black text-[10px] md:text-xs font-black uppercase tracking-widest hover:bg-white transition-all shadow-[0_0_20px_rgba(204,255,0,0.2)] whitespace-nowrap"
          >
            {session ? "Dashboard" : "Get Juice"}
          </button>
        </div>
      </nav>

      {/* ━━━ HERO & TERMINAL ━━━ */}
      <section className="relative pt-32 lg:pt-40 pb-20 px-6 lg:px-12 xl:px-20 z-10">

        <div className="w-full max-w-[1600px] mx-auto relative z-10 flex flex-col lg:flex-row items-center justify-between gap-16 xl:gap-24">
          
          {/* Hero Content */}
          <div className="flex-1 text-center lg:text-left flex flex-col items-center lg:items-start">
            <div className="inline-flex flex-col sm:flex-row items-center gap-3 px-4 py-2 rounded-xl border border-white/10 bg-[#0f141f] mb-8 lg:mb-10 animate-fade-up">
              <div className="flex items-center">
                <Sparkles className="h-3 w-3 text-[#ccff00] mr-2" />
                <span className="text-[10px] tracking-[0.2em] uppercase font-bold text-white/70">
                  Open Source · Free Forever · Roblox OAuth 2.0
                </span>
              </div>
            </div>

            {/* Headline */}
            <h1 className="text-[40px] sm:text-[60px] md:text-[85px] font-black leading-[0.9] tracking-[-0.04em] mb-8 animate-fade-up-delay-1 text-white">
              The Open-Source <br /> 
              <span className="font-space italic bg-gradient-to-r from-red-500 via-orange-500 to-red-600 bg-clip-text text-transparent px-2">AI Code Tool</span> <br /> 
              for Roblox.
            </h1>

            {/* Subtext */}
            <p className="max-w-[500px] text-lg md:text-xl text-white/70 mb-10 leading-relaxed animate-fade-up-delay-2 font-medium">
              Describe what you want to build. Apple Juice generates Luau code and injects it directly into Studio — no copy-pasting required.
            </p>

            {/* Buttons */}
            <div className="flex flex-col sm:flex-row items-center gap-4 w-full sm:w-auto animate-fade-up-delay-2">
              <button
                onClick={() => session ? window.location.href = "/dashboard" : setShowAuthGuide(true)}
                className="h-14 w-full sm:w-auto px-10 bg-[#ccff00] text-black font-bold uppercase tracking-wider text-sm flex items-center justify-center gap-2 hover:bg-[#b3e600] hover:-translate-y-1 active:scale-95 transition-all border border-transparent rounded-xl shadow-[0_10px_30px_rgba(204,255,0,0.2)]"
              >
                Get Started
                <ArrowRight className="h-4 w-4" />
              </button>

              <button className="h-14 w-full sm:w-auto px-10 bg-transparent text-white font-bold uppercase tracking-wider text-sm flex items-center justify-center gap-2 hover:bg-white/5 hover:-translate-y-1 active:scale-95 transition-all border border-white/20 rounded-xl">
                Watch Demo
              </button>
            </div>
          </div>

          {/* Terminal Mockup */}
          <div id="terminal" className="flex-1 w-full max-w-2xl lg:max-w-none mt-10 lg:mt-0">
            <div className="rounded-2xl border border-white/10 bg-[#0f141f] overflow-hidden relative z-10 shadow-2xl flex flex-col h-[480px] xl:h-[400px]">
              <div className="flex items-center gap-2 px-4 py-3 border-b border-white/10 bg-[#060a12] flex-shrink-0 h-[45px]">
                <div className="flex gap-1.5">
                  <div className="h-3 w-3 rounded-full bg-[#ff5f57]" />
                  <div className="h-3 w-3 rounded-full bg-[#febc2e]" />
                  <div className="h-3 w-3 rounded-full bg-[#28c840]" />
                </div>
                <span className="ml-3 text-[11px] text-white/50 font-mono">Apple Juice — AI Output</span>
              </div>

              <div className="flex flex-col xl:flex-row flex-1 h-[435px] xl:h-[355px]">
                <div className="flex-1 border-b xl:border-b-0 xl:border-r border-white/10 bg-[#0a0e1a]/50 relative overflow-hidden">
                  <div className="absolute inset-0 overflow-y-auto p-4">
                    <AnimatePresence mode="wait">
                      <motion.pre
                        key={activeScriptIndex}
                        initial={{ opacity: 0, x: 10 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: -10 }}
                        transition={{ duration: 0.15 }}
                        className="font-mono text-[10px] xl:text-[11px] leading-relaxed"
                      >
                      <Highlight
                        theme={luauTheme}
                        code={MULTI_SCRIPTS[activeScriptIndex].code}
                        language="lua"
                      >
                        {({ tokens, getTokenProps }) => (
                          <code>
                            {tokens.map((line, i) => (
                              <div key={i}>
                                {line.map((token, key) => (
                                  <span key={key} {...getTokenProps({ token })} />
                                ))}
                              </div>
                            ))}
                          </code>
                        )}
                      </Highlight>
                    </motion.pre>
                  </AnimatePresence>
                </div>
              </div>

              <div className="w-full xl:w-56 p-3 bg-[#060a12] flex-shrink-0 flex flex-row xl:flex-col gap-2 overflow-x-auto xl:overflow-visible no-scrollbar border-t border-white/5 xl:border-none">
                  <p className="hidden xl:block text-[9px] tracking-[0.2em] uppercase font-bold text-white/50 mb-1 ml-1">
                    Generated Files
                  </p>
                  {MULTI_SCRIPTS.map((s, i) => (
                    <div
                      key={i}
                      onClick={() => setActiveScriptIndex(i)}
                      className={`flex flex-shrink-0 min-w-[150px] xl:min-w-0 items-center justify-between p-2.5 rounded-xl border transition-all duration-300 cursor-pointer ${
                        activeScriptIndex === i 
                          ? 'bg-white/10 border-white/30' 
                          : 'bg-[#1a1d23]/50 border-transparent hover:border-white/10'
                      }`}
                    >
                      <div className="truncate pr-2">
                        <p className={`text-xs md:text-[13px] font-semibold truncate ${activeScriptIndex === i ? 'text-white' : 'text-white/60'}`}>{s.name}</p>
                        <p className="text-[10px] md:text-[11px] text-white/40 mt-0.5 md:mt-1 truncate">
                          {s.type}
                        </p>
                      </div>
                      <span className="text-[10px] md:text-[11px] text-white/20 font-mono flex-shrink-0">{s.lines}L</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ━━━ FEATURES ━━━ */}
      <section id="features" className="px-6 pb-32 relative overflow-hidden">
        <div className="max-w-[1200px] mx-auto relative z-10">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-medium tracking-tight text-white mb-4">
              We handle the hard stuff
            </h2>
            <p className="text-white/50 text-lg">
              Safe code generation, automatic file sync with Studio and more
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* LEFT COLUMN */}
            <div className="flex flex-col gap-6">
              {/* No More Copy Pasting */}
              <div className="group rounded-3xl bg-[#13151a] border border-white/5 overflow-hidden relative flex flex-col h-[350px] transition-all duration-500 hover:border-white/10">
                {/* Visual */}
                <div className="absolute inset-0 top-0 h-[220px] flex items-center justify-center" style={{ perspective: "1000px" }}>
                  <div className="relative w-[240px] h-[140px] mt-4" style={{ transformStyle: "preserve-3d" }}>
                    {/* Apple Juice Auto Sync Card */}
                    <div className="absolute inset-0 bg-[#1e1e24]/80 backdrop-blur-md rounded-2xl border border-white/10 p-4 shadow-2xl transform -rotate-[12deg] -translate-x-4 -translate-y-4 group-hover:rotate-0 group-hover:translate-x-0 group-hover:translate-y-0 transition-all duration-700 ease-out z-10">
                      <div className="flex items-center gap-3 mb-3">
                        <div className="w-8 h-8 rounded-full bg-[#7c3aed] flex items-center justify-center text-white shadow-[0_0_15px_rgba(124,58,237,0.5)]">
                          <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                            <path d="M13 10V3L4 14h7v7l9-11h-7z" />
                          </svg>
                        </div>
                        <span className="text-sm font-bold text-white/90">Apple Juice Auto Sync</span>
                      </div>
                      <p className="text-base font-medium text-white mb-2">No copy-paste! Let me handle this.</p>
                      <div className="flex items-center gap-2">
                        <span className="text-[10px] uppercase tracking-widest text-[#7c3aed] font-bold">Automatic</span>
                        <div className="h-1 w-1 rounded-full bg-white/20" />
                        <span className="text-[10px] text-white/40">Real-time</span>
                      </div>
                    </div>

                    {/* Roblox Studio Card */}
                    <div className="absolute inset-0 bg-[#16161c]/90 backdrop-blur-md rounded-2xl border border-white/5 p-4 shadow-xl transform rotate-[8deg] translate-x-8 translate-y-12 group-hover:rotate-0 group-hover:translate-x-0 group-hover:translate-y-16 transition-all duration-700 ease-out z-20">
                      <div className="flex items-center gap-3 mb-3">
                        <div className="w-8 h-8 rounded-full bg-[#7c3aed]/20 border border-[#7c3aed]/50 flex items-center justify-center text-[#7c3aed]">
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="3" viewBox="0 0 24 24">
                            <polyline points="20 6 9 17 4 12" />
                          </svg>
                        </div>
                        <span className="text-sm font-bold text-white/80">Roblox Studio</span>
                      </div>
                      <p className="text-sm text-white/60 leading-tight">6 scripts received from Apple Juice sync.</p>
                      <p className="text-[11px] text-[#7c3aed] font-mono mt-3">Automatic</p>
                    </div>
                  </div>
                </div>
                {/* Text content */}
                <div className="mt-auto p-6 relative z-10 bg-gradient-to-t from-[#13151a] via-[#13151a] to-transparent pt-12 pointer-events-none">
                  <div className="w-8 h-8 rounded-lg mb-4 flex items-center justify-center bg-white/5">
                    <svg className="w-5 h-5 text-indigo-400" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"/></svg>
                  </div>
                  <h3 className="text-lg font-semibold text-white mb-2">No More Copy-Pasting</h3>
                  <p className="text-sm text-white/50">Files automatically sync with Studio.</p>
                </div>
              </div>

              {/* Agent Playtest */}
              <div className="group rounded-3xl bg-[#13151a] border border-white/5 overflow-hidden relative flex flex-col h-[200px] transition-all duration-500 hover:border-white/10">
                <div className="absolute inset-0 top-0 h-[100px] flex items-center justify-center overflow-hidden">
                  <div className="relative w-[85%] bg-[#060a12]/80 rounded-lg border border-white/5 p-2.5 flex flex-col gap-1.5 overflow-hidden group-hover:border-[#7c3aed]/20 transition-colors duration-500 mt-6">
                    <div className="flex flex-col gap-1.5">
                      <div className="flex items-center gap-2">
                        <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                        <span className="text-[9px] text-white/50 font-mono">Running behavior tests...</span>
                      </div>
                      <span className="text-[9px] text-red-400 font-mono opacity-0 group-hover:opacity-100 transition-opacity duration-300 delay-100">[Error] nil value in BulletManager.lua:42</span>
                      <span className="text-[9px] text-[#7c3aed] font-mono opacity-0 group-hover:opacity-100 transition-opacity duration-300 delay-300">{`> Analyzing fix... Appending guard.`}</span>
                      <span className="text-[9px] text-emerald-400 font-mono opacity-0 group-hover:opacity-100 transition-opacity duration-300 delay-500">{`> Test passed. 0 issues remaining.`}</span>
                    </div>
                  </div>
                </div>
                <div className="mt-auto p-5 relative z-10 bg-gradient-to-t from-[#13151a] via-[#13151a] to-transparent pt-8 pointer-events-none">
                  <div className="w-7 h-7 rounded-lg mb-2 flex items-center justify-center bg-white/5">
                    <svg className="w-4 h-4 text-indigo-400" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h0m6 0h0m-3 4h0"/></svg>
                  </div>
                  <h3 className="text-base font-semibold text-white mb-1">Agent Playtest</h3>
                  <p className="text-[11px] text-white/50 leading-tight">Apple Juice playtests your game and fixes issues automatically.</p>
                </div>
              </div>
            </div>

            {/* MIDDLE COLUMN */}
            <div className="flex flex-col">
              {/* Cross-Compatibility */}
              <div className="group rounded-3xl bg-[#13151a] border border-white/5 overflow-hidden relative flex flex-col h-full min-h-[574px] transition-all duration-500 hover:border-white/10">
                {/* Visual */}
                <div className="absolute inset-0 flex items-center justify-center overflow-hidden">
                  {/* Phone frame */}
                  <div className="relative w-[240px] h-[480px] rounded-[36px] border-[6px] border-[#2a2d36] bg-black shadow-2xl group-hover:translate-y-[-10px] transition-transform duration-700 ease-out flex flex-col items-center justify-center overflow-hidden">
                    <div className="absolute top-0 inset-x-0 h-6 flex justify-center">
                      <div className="w-24 h-5 bg-[#2a2d36] rounded-b-xl" />
                    </div>
                    {/* App UI mockup */}
                    <div className="absolute inset-0 mt-8 px-4 flex flex-col opacity-40">
                       <div className="h-10 border-b border-white/10 flex justify-between items-center">
                         <div className="w-4 h-4 rounded bg-white/20" />
                         <div className="w-16 h-3 rounded bg-white/20" />
                         <div className="w-4 h-4 rounded bg-white/20" />
                       </div>
                       <div className="mt-4 w-full h-8 rounded-lg bg-white/10" />
                       <div className="mt-4 w-3/4 h-3 rounded bg-white/10" />
                       <div className="mt-2 w-1/2 h-3 rounded bg-white/10" />
                    </div>
                    
                    <div className="z-10 bg-black/60 backdrop-blur-md px-6 py-3 rounded-2xl border border-white/10 shadow-2xl transform scale-95 group-hover:scale-105 transition-transform duration-700">
                      <h4 className="text-2xl font-black tracking-widest text-white">COMING</h4>
                    </div>

                    {/* Keyboard mockup */}
                    <div className="absolute bottom-2 inset-x-2 h-40 bg-[#1e2128] rounded-2xl flex flex-col gap-1 p-2 opacity-50 transform translate-y-4 group-hover:translate-y-0 transition-transform duration-700">
                       <div className="flex justify-center gap-1">
                         {Array.from({length: 10}).map((_,i) => <div key={i} className="h-8 w-5 bg-white/10 rounded" />)}
                       </div>
                       <div className="flex justify-center gap-1">
                         {Array.from({length: 9}).map((_,i) => <div key={i} className="h-8 w-5 bg-white/10 rounded" />)}
                       </div>
                       <div className="flex justify-center gap-1">
                         {Array.from({length: 7}).map((_,i) => <div key={i} className="h-8 w-5 bg-white/10 rounded" />)}
                       </div>
                    </div>
                  </div>
                </div>
                {/* Text content */}
                <div className="mt-auto p-6 relative z-10 bg-gradient-to-t from-[#13151a] via-[#13151a]/90 to-transparent pt-20">
                  <div className="w-8 h-8 rounded-lg mb-4 flex items-center justify-center">
                    <svg className="w-6 h-6 text-indigo-400" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>
                  </div>
                  <h3 className="text-lg font-semibold text-white mb-2">Cross-Compatibility</h3>
                  <p className="text-sm text-white/50">Code small snippets or edit configs from your phone, tablet, or desktop.</p>
                </div>
              </div>
            </div>

            {/* RIGHT COLUMN */}
            <div className="flex flex-col gap-6">
              {/* Version Control */}
              <div className="group rounded-3xl bg-[#13151a] border border-white/5 overflow-hidden relative flex flex-col h-[200px] transition-all duration-500 hover:border-white/10">
                <div className="absolute inset-0 top-0 h-[100px] flex items-center justify-center mt-4">
                  <div className="relative w-[180px] h-[60px] flex items-center justify-center">
                    {/* SVG Connections */}
                    <svg className="absolute inset-0 w-full h-full" style={{ filter: "drop-shadow(0 0 8px rgba(124,58,237,0.15))" }}>
                      <motion.path 
                        d="M 20 30 L 70 30 L 120 15 L 160 15" 
                        fill="none" 
                        stroke="rgba(255,255,255,0.05)" 
                        strokeWidth="2"
                        animate={{ stroke: ["rgba(255,255,255,0.05)", "rgba(124,58,237,0.4)", "rgba(255,255,255,0.05)"] }}
                        transition={{ duration: 3, repeat: Infinity }}
                      />
                      <motion.path 
                        d="M 70 30 L 120 45 L 160 45" 
                        fill="none" 
                        stroke="rgba(255,255,255,0.05)" 
                        strokeWidth="2"
                        animate={{ stroke: ["rgba(255,255,255,0.05)", "rgba(204,255,0,0.4)", "rgba(255,255,255,0.05)"] }}
                        transition={{ duration: 3, repeat: Infinity, delay: 1.5 }}
                      />
                    </svg>
                    
                    {/* Nodes */}
                    <div className="absolute left-[10px] w-5 h-5 rounded-full bg-[#1e2128] border border-white/10 flex items-center justify-center z-10 shadow-lg">
                      <div className="w-1.5 h-1.5 rounded-full bg-white/20" />
                    </div>
                    
                    <div className="absolute left-[60px] w-6 h-6 rounded-full bg-[#252830] border border-white/20 flex items-center justify-center z-10 group-hover:scale-110 transition-all duration-500">
                      <div className="w-2 h-2 rounded-full bg-indigo-400/50 shadow-[0_0_10px_rgba(129,140,248,0.5)]" />
                    </div>

                    <div className="absolute left-[110px] top-[5px] w-8 h-8 rounded-full bg-[#1e1e24] border border-[#7c3aed]/30 flex items-center justify-center z-10 group-hover:border-[#7c3aed] group-hover:scale-110 transition-all duration-500 shadow-xl">
                      <span className="text-[9px] font-bold text-white group-hover:text-[#7c3aed]">v3.1</span>
                    </div>

                    <div className="absolute left-[110px] bottom-[5px] w-8 h-8 rounded-full bg-[#1e1e24] border border-[#ccff00]/30 flex items-center justify-center z-10 group-hover:border-[#ccff00] group-hover:scale-110 transition-all duration-500 shadow-xl">
                      <span className="text-[9px] font-bold text-white group-hover:text-[#ccff00]">v3.2</span>
                    </div>
                  </div>
                </div>
                <div className="mt-auto p-5 relative z-10 bg-gradient-to-t from-[#13151a] via-[#13151a] to-transparent pt-8 pointer-events-none">
                  <div className="w-7 h-7 rounded-lg mb-2 flex items-center justify-center bg-white/5">
                    <svg className="w-4 h-4 text-indigo-400" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                  </div>
                  <h3 className="text-base font-semibold text-white mb-1">Version Control</h3>
                  <p className="text-[11px] text-white/50 leading-tight">Control your project and rollback to any past prompt iterations.</p>
                </div>
              </div>

              {/* Fast and Accurate */}
              <div className="group rounded-3xl bg-[#13151a] border border-white/5 overflow-hidden relative flex flex-col h-[350px] transition-all duration-500 hover:border-white/10">
                {/* Visual */}
                <div className="absolute inset-0 top-0 h-[220px] flex items-center justify-center overflow-hidden">
                  <motion.div 
                    className="w-full px-10 flex flex-col gap-3 transform -rotate-[10deg] translate-y-4"
                    animate={{ y: [0, -224] }}
                    transition={{ 
                      duration: 12, 
                      repeat: Infinity, 
                      ease: "linear"
                    }}
                    whileHover={{ 
                      transition: { duration: 40, repeat: Infinity, ease: "linear" }
                    }}
                  >
                    {[...Array(4)].map((_, i) => (
                      <div key={i} className="flex flex-col gap-3">
                        <div className="w-full bg-[#1e2128]/80 border border-white/5 p-3 rounded-xl flex items-center gap-3 shadow-lg hover:scale-110 hover:bg-[#252832] transition-all duration-300 group/item cursor-default">
                          <div className="w-5 h-5 rounded-full bg-[#7c3aed]/20 border border-[#7c3aed]/50 flex items-center justify-center text-[#7c3aed]">
                            <svg className="w-3 h-3" fill="none" stroke="currentColor" strokeWidth="3" viewBox="0 0 24 24"><polyline points="20 6 9 17 4 12"/></svg>
                          </div>
                          <span className="text-sm font-medium text-white/70 group-hover/item:text-white">1. Apple Juice context data</span>
                        </div>

                        <div className="w-full bg-[#252830]/90 border border-white/10 p-3 rounded-xl flex items-center gap-3 shadow-xl hover:scale-110 hover:bg-[#2a2e38] transition-all duration-300 group/item cursor-default">
                          <div className="w-5 h-5 rounded-full bg-[#7c3aed]/20 border border-[#7c3aed]/50 flex items-center justify-center text-[#7c3aed]">
                            <svg className="w-3 h-3" fill="none" stroke="currentColor" strokeWidth="3" viewBox="0 0 24 24"><polyline points="20 6 9 17 4 12"/></svg>
                          </div>
                          <span className="text-sm font-medium text-white/80 group-hover/item:text-white">2. Project analysis</span>
                        </div>

                        <div className="w-full bg-[#2a2d36] border border-white/20 p-3 rounded-xl flex items-center gap-3 shadow-2xl hover:scale-110 hover:bg-[#323640] transition-all duration-300 group/item cursor-default">
                          <div className="w-5 h-5 rounded-full bg-[#7c3aed]/20 border border-[#7c3aed]/50 flex items-center justify-center text-[#7c3aed]">
                            <svg className="w-3 h-3" fill="none" stroke="currentColor" strokeWidth="3" viewBox="0 0 24 24"><polyline points="20 6 9 17 4 12"/></svg>
                          </div>
                          <span className="text-sm font-semibold text-white">3. Model generation</span>
                        </div>

                        <div className="w-full bg-[#1e1e24] border border-white/10 p-3 rounded-xl flex items-center gap-3 shadow-lg hover:scale-110 hover:bg-[#25252d] transition-all duration-300 group/item cursor-default">
                          <div className="w-5 h-5 rounded-full bg-white/10 flex items-center justify-center text-white/40">
                             <div className="w-1 h-1 rounded-full bg-white/40" />
                          </div>
                          <span className="text-sm font-medium text-white/50 group-hover/item:text-white">Prompt received</span>
                        </div>
                      </div>
                    ))}
                  </motion.div>
                </div>
                {/* Text content */}
                <div className="mt-auto p-6 relative z-10 bg-gradient-to-t from-[#13151a] via-[#13151a] to-transparent pt-12 pointer-events-none">
                  <div className="w-8 h-8 rounded-lg mb-4 flex items-center justify-center bg-white/5">
                    <svg className="w-5 h-5 text-indigo-400" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
                  </div>
                  <h3 className="text-lg font-semibold text-white mb-2">Fast and Accurate</h3>
                  <p className="text-sm text-white/50">Industry leading inference speed for the best developer experience.</p>
                </div>
              </div>
            </div>

        </div>
      </section>

      {/* ━━━ PRICING ━━━ */}
      <section id="pricing" className="px-6 pb-20 relative pt-10">
        <div className="max-w-[1000px] mx-auto relative z-10">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-5xl font-black uppercase tracking-[-0.02em] text-white mb-6">
              Pick Your <span className="text-[#ccff00]">Squeeze</span>
            </h2>
            <div className="inline-flex bg-[#1a1d24] p-1.5 rounded-2xl border border-white/10 items-center">
              <button 
                onClick={() => setIsRobux(false)}
                className={`px-6 py-2 rounded-xl text-sm font-bold transition-all ${!isRobux ? "bg-white text-black shadow-lg" : "text-white/50 hover:text-white"}`}
              >
                Pay in USD
              </button>
              <button 
                onClick={() => setIsRobux(true)}
                className={`px-6 py-2 rounded-xl text-sm font-bold transition-all flex items-center gap-2 ${isRobux ? "bg-[#00A2FF] text-white shadow-[0_0_15px_rgba(0,162,255,0.4)]" : "text-white/50 hover:text-white"}`}
              >
                Pay in Robux
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
            {/* LITE PLAN */}
            <div className="bg-[#13151a] border border-white/5 rounded-[2rem] p-8 flex flex-col hover:border-white/10 transition-all duration-300">
              <div className="text-[#ccff00] text-sm font-bold uppercase tracking-wider mb-2">Lite Plan</div>
              <div className="text-4xl font-black text-white mb-2">{isRobux ? "0 R$" : "$0"}<span className="text-lg text-white/40 font-normal"> / forever</span></div>
              <p className="text-sm text-white/50 mb-8 border-b border-white/5 pb-8">Perfect for testing the waters and small scripts.</p>
              
              <ul className="flex flex-col gap-4 mb-8 text-sm">
                <li className="flex items-center gap-3 text-white/80"><svg className="w-5 h-5 text-[#ccff00]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"/></svg> 1 Credit per day</li>
                <li className="flex items-center gap-3 text-white/80"><svg className="w-5 h-5 text-[#ccff00]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"/></svg> Basic Code Generation</li>
                <li className="flex items-center gap-3 text-white/40"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"/></svg> No Stacking</li>
                <li className="flex items-center gap-3 text-white/40"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"/></svg> 1 Project Limit</li>
              </ul>
            </div>

            {/* PRO PLAN */}
            <div className="bg-gradient-to-b from-[#1a1d24] to-[#13151a] border border-[#ccff00]/30 rounded-[2rem] p-8 flex flex-col relative transform md:-translate-y-4 shadow-[0_0_30px_rgba(204,255,0,0.1)]">
              <div className="absolute -top-4 left-1/2 -translate-x-1/2 bg-[#ccff00] text-black text-xs font-black uppercase tracking-wider py-1.5 px-4 rounded-full">Most Popular</div>
              <div className="text-white text-sm font-bold uppercase tracking-wider mb-2">Pro Plan</div>
              <div className="text-4xl font-black text-white mb-2">{isRobux ? "1,200 R$" : "$9.99"}<span className="text-lg text-white/40 font-normal"> / month</span></div>
              <p className="text-sm text-white/50 mb-8 border-b border-white/5 pb-8">Everything you need to ship a complete game.</p>
              
              <ul className="flex flex-col gap-4 mb-8 text-sm">
                <li className="flex items-center gap-3 text-white"><svg className="w-5 h-5 text-[#ccff00]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"/></svg> <strong>4 Credits per day</strong> (+20 bonus)</li>
                <li className="flex items-center gap-3 text-white/80"><svg className="w-5 h-5 text-[#ccff00]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"/></svg> Stack up to 10 Credits</li>
                <li className="flex items-center gap-3 text-white/80"><svg className="w-5 h-5 text-[#ccff00]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"/></svg> Claude 3.5 & GPT-4o Access</li>
                <li className="flex items-center gap-3 text-white/80"><svg className="w-5 h-5 text-[#ccff00]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"/></svg> Create up to 10 Projects</li>
              </ul>
              
              <button className="mt-auto w-full bg-[#ccff00] text-black font-bold py-3 rounded-xl hover:bg-[#b3e600] transition-colors">Upgrade to Pro</button>
            </div>

            {/* ULTRA PLAN */}
            <div className="bg-[#13151a] border border-[#7c3aed]/30 rounded-[2rem] p-8 flex flex-col hover:border-[#7c3aed]/50 transition-all duration-300 relative shadow-[0_0_30px_rgba(124,58,237,0.05)]">
              <div className="text-[#7c3aed] text-sm font-bold uppercase tracking-wider mb-2">Ultra Plan</div>
              <div className="text-4xl font-black text-white mb-2">{isRobux ? "2,500 R$" : "$19.99"}<span className="text-lg text-white/40 font-normal"> / month</span></div>
              <p className="text-sm text-white/50 mb-8 border-b border-white/5 pb-8">For serious developers who want AI automation.</p>
              
              <ul className="flex flex-col gap-4 mb-8 text-sm">
                <li className="flex items-center gap-3 text-white"><svg className="w-5 h-5 text-[#7c3aed]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"/></svg> <strong>12 Credits per day</strong> (+100 bonus)</li>
                <li className="flex items-center gap-3 text-white/80"><svg className="w-5 h-5 text-[#7c3aed]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"/></svg> Stack up to 40 Credits</li>
                <li className="flex items-center gap-3 text-white/80"><svg className="w-5 h-5 text-[#7c3aed]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"/></svg> Full Project RAG Context</li>
                <li className="flex items-center gap-3 text-white/80"><svg className="w-5 h-5 text-[#7c3aed]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"/></svg> Unlimited Projects</li>
              </ul>
              
              <button className="mt-auto w-full bg-[#1e2128] text-white font-bold py-3 rounded-xl hover:bg-[#252830] transition-colors border border-[#7c3aed]/50">Get Ultra</button>
            </div>
          </div>

          {/* JUICE PACKS */}
          <div className="bg-[#0f1115] border border-white/5 rounded-3xl p-8 md:p-10">
            <div className="text-center mb-8">
              <h3 className="text-2xl font-black text-white">Need a quick squeeze?</h3>
              <p className="text-white/50 text-sm mt-2">Grab a one-time Juice Pack to refill your credits instantly.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="bg-[#13151a] border border-white/10 rounded-2xl p-6 flex flex-col text-center hover:border-white/20 transition-colors">
                <div className="text-white/60 text-sm font-semibold mb-2">Small Squeeze</div>
                <div className="text-2xl font-black text-white mb-1">{isRobux ? "350 R$" : "$2.99"}</div>
                <div className="text-sm text-[#ccff00] font-bold mb-6">15 Credits</div>
                <button className="w-full bg-white text-black font-bold py-2.5 rounded-lg text-sm hover:bg-gray-200 transition-colors">Purchase</button>
              </div>
              <div className="bg-[#1a1d24] border border-[#ccff00]/30 rounded-2xl p-6 flex flex-col text-center relative shadow-[0_0_20px_rgba(204,255,0,0.05)]">
                <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-[#ccff00] text-black text-[10px] font-black uppercase tracking-wider py-1 px-3 rounded-full">Value</div>
                <div className="text-white/60 text-sm font-semibold mb-2">Big Squeeze</div>
                <div className="text-2xl font-black text-white mb-1">{isRobux ? "950 R$" : "$7.99"}</div>
                <div className="text-sm text-[#ccff00] font-bold mb-6">50 Credits</div>
                <button className="w-full bg-[#ccff00] text-black font-bold py-2.5 rounded-lg text-sm hover:bg-[#b3e600] transition-colors">Purchase</button>
              </div>
              <div className="bg-[#13151a] border border-white/10 rounded-2xl p-6 flex flex-col text-center hover:border-white/20 transition-colors">
                <div className="text-white/60 text-sm font-semibold mb-2">Industrial Squeeze</div>
                <div className="text-2xl font-black text-white mb-1">{isRobux ? "3,000 R$" : "$24.99"}</div>
                <div className="text-sm text-[#ccff00] font-bold mb-6">200 Credits</div>
                <button className="w-full bg-white text-black font-bold py-2.5 rounded-lg text-sm hover:bg-gray-200 transition-colors">Purchase</button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ━━━ FAQ ━━━ */}
      <section id="faq" className="px-6 pb-20 relative">
        <div className="max-w-[700px] mx-auto relative z-10">
          <div className="text-center mb-8">
            <h2 className="text-3xl md:text-5xl font-black uppercase tracking-[-0.02em] text-white">
              Questions?
            </h2>
          </div>
          <div className="rounded-xl border border-white/20 bg-[#1a1d24] px-6 shadow-2xl shadow-blue-500/5">
            {FAQ_ITEMS.map((item, i) => (
              <FaqItem key={i} question={item.question} answer={item.answer} />
            ))}
          </div>
        </div>
      </section>

      {/* ━━━ BOTTOM CTA ━━━ */}
      <section className="px-6 pb-24">
        <div className="max-w-[800px] mx-auto text-center p-10 lg:p-12 rounded-[2rem] bg-[#0f141f] border border-white/10 relative overflow-hidden">
          <div className="relative z-10">
            <h2 className="text-3xl sm:text-4xl font-black uppercase tracking-[-0.02em] mb-4">
              Ship your next feature tonight.
            </h2>
            <p className="text-[15px] text-white/70 mb-8 max-w-xl mx-auto font-medium">
              Join Roblox developers who go from idea to working Luau code in minutes. <br/> <strong className="text-white mt-1 block">Ready to ditch the credits? Bring your own API key and get zero limits.</strong>
            </p>
            
            <button
              onClick={() => session ? window.location.href = "/dashboard" : setShowAuthGuide(true)}
              className="h-14 w-full sm:w-auto px-10 bg-[#ccff00] text-black font-bold uppercase tracking-wider text-sm flex items-center justify-center gap-2 hover:bg-[#b3e600] transition-colors border border-transparent mx-auto rounded-xl"
            >
              Start Building for Free
              <ArrowRight className="h-4 w-4" />
            </button>
          </div>
        </div>
      </section>

      {/* ━━━ FOOTER ━━━ */}
      <footer className="border-t border-white/10 px-6 py-12 bg-[#060a12]">
        <div className="max-w-[1200px] mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            <div className="h-7 w-7 rounded-lg bg-[#ccff00] flex items-center justify-center shadow-[0_0_15px_rgba(204,255,0,0.4)]">
              <svg viewBox="0 0 24 24" className="h-4 w-4 text-black" fill="currentColor">
                <path d="M5.2 6.5L7.5 3h9l2.3 3.5H5.2z" fillOpacity="0.8" />
                <path d="M5 8v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8H5z" />
                <path d="M15 3V1.5A1.5 1.5 0 0 0 13.5 0H12" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
                <path d="M14.5 14.5c0 1.5-1 2.5-2.5 2.5s-2.5-1-2.5-2.5 1-2.5 2.5-2.5c.3 0 .7.1 1 .2-.3.4-.3 1 0 1.4.3.4.9.4 1.3.1.1.2.2.5.2.8zM12.5 11c0-1-.8-1.5-1.5-1.5 0 1 .8 1.5 1.5 1.5z" fill="#ccff00" />
              </svg>
            </div>
            <div className="flex flex-col">
              <span className="text-lg font-black tracking-widest uppercase text-white">Apple Juice</span>
              <span className="text-[10px] text-white/50 mt-1 uppercase tracking-tighter font-medium">Made from developers to developers</span>
            </div>
          </div>
          
          <div className="flex items-center gap-6">
            <a href="#" className="text-sm text-white/60 hover:text-[#ccff00] transition-colors">Twitter</a>
            <a href="#" className="text-sm text-white/60 hover:text-[#ccff00] transition-colors">GitHub</a>
            <a href="#" className="text-sm text-white/60 hover:text-[#ccff00] transition-colors">Discord</a>
            <a href="mailto:info@apple-juice.online" className="text-sm text-white/60 hover:text-[#ccff00] transition-colors">Support</a>
          </div>

          <p className="text-[11px] text-white/40 text-center md:text-right max-w-xs">
            Independent open-source project. Not affiliated with or endorsed by Roblox Corporation. Roblox® is a trademark of Roblox Corporation.
          </p>
        </div>
      </footer>

      {/* ━━━ OAUTH GUIDE MODAL ━━━ */}
      {showAuthGuide && (
        <div 
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4"
          onClick={(e) => {
            if (e.target === e.currentTarget) setShowAuthGuide(false);
          }}
        >
          <div className="w-full max-w-2xl bg-[#111113] border border-white/10 rounded-2xl shadow-2xl overflow-hidden flex flex-col relative animate-in zoom-in-95 duration-200">
            {/* Header */}
            <div className="h-16 flex items-center justify-between px-8 border-b border-white/5 bg-[#0a0a0c]">
              <span className="font-bold text-lg tracking-wide text-white">How we authenticate you</span>
              <button onClick={() => setShowAuthGuide(false)} className="sm:hidden text-white/50 hover:text-white p-2 -mr-2">
                <svg viewBox="0 0 24 24" className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6L6 18M6 6l12 12"/></svg>
              </button>
            </div>
            
            {/* Body */}
            <div className="p-8 sm:p-10 overflow-y-auto max-h-[75vh]">
              <p className="text-[#8a8f98] text-base leading-relaxed mb-8">
                Clicking &ldquo;Continue&rdquo; will open an <strong className="text-white">official authorization screen</strong> for either Roblox or Google. Here is exactly what is shared and how it is used:
              </p>
              
              <div className="space-y-6">
                {/* Section 1 */}
                <div className="bg-[#1a1d24] border border-white/5 rounded-xl p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="h-8 w-8 rounded-full bg-blue-500/10 flex items-center justify-center border border-blue-500/20">
                      <span className="text-blue-400 font-bold">1</span>
                    </div>
                    <h3 className="text-lg font-semibold text-white">Your Roblox Profile (via OAuth 2.0)</h3>
                  </div>
                  <p className="text-sm text-[#8a8f98] mb-4">
                    Roblox will ask you to grant Apple Juice access to your <strong className="text-white">User ID</strong> and <strong className="text-white">public profile</strong>, as shown on Roblox&apos;s consent screen.
                  </p>
                  <ul className="text-sm text-[#8a8f98] space-y-2 list-disc pl-5">
                    <li>We use your User ID/Email to identify your dashboard session.</li>
                    <li><strong className="text-[#ccff00]">We NEVER receive your password.</strong></li>
                    <li><strong className="text-[#ccff00]">We NEVER receive your Robux balance or private data.</strong></li>
                    <li>You can revoke access at any time via your account provider settings.</li>
                  </ul>
                  {/* Why OAuth? callout */}
                  <div className="mt-4 flex items-start gap-2.5 p-3 rounded-lg bg-[#090a0d] border border-white/10">
                    <span className="text-[#ccff00] text-sm font-bold flex-shrink-0 mt-0.5">?</span>
                    <p className="text-xs text-[#8a8f98] leading-relaxed">
                      <strong className="text-white">Why OAuth 2.0?</strong>{" "}
                      OAuth ensures we never touch your password and allows you to revoke Apple Juice&apos;s access instantly from your Roblox Security settings — no contacting us required.
                    </p>
                  </div>
                </div>

                {/* Section 2 */}
                <div className="bg-[#1a1d24] border border-white/5 rounded-xl p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="h-8 w-8 rounded-full bg-[#ccff00]/10 flex items-center justify-center border border-[#ccff00]/20">
                      <span className="text-[#ccff00] font-bold">2</span>
                    </div>
                    <h3 className="text-lg font-semibold text-white">The Studio Plugin (separate install)</h3>
                  </div>
                  <p className="text-sm text-[#8a8f98] mb-4">
                    After signing in, you can install the Apple Juice plugin from the Roblox Creator Store. Here is exactly what it does — and what it does not:
                  </p>
                  <ul className="text-sm text-[#8a8f98] space-y-3">
                    <li className="flex items-start gap-2">
                       <span className="text-yellow-500 mt-0.5 flex-shrink-0">●</span> 
                       <span><strong className="text-white">Write Scripts (Medium Risk):</strong> Creates or overwrites scripts in your place <em>only</em> when you explicitly trigger a generation.</span>
                    </li>
                    <li className="flex items-start gap-2">
                       <span className="text-green-500 mt-0.5 flex-shrink-0">●</span> 
                       <span><strong className="text-white">Read Explorer Tree (Low Risk):</strong> Reads your folder structure (e.g. <code className="text-white/60 bg-white/5 px-1 rounded">ReplicatedStorage</code>) so the AI places files correctly.</span>
                    </li>
                    <li className="flex items-start gap-2">
                       <span className="text-white/30 mt-0.5 flex-shrink-0">●</span> 
                       <span><strong className="text-white">No account access:</strong> The plugin cannot read your Roblox credentials, Robux, or any data outside the open Studio session.</span>
                    </li>
                  </ul>
                </div>

                {/* Step 3 — Next Steps */}
                <div className="bg-[#1a1d24] border border-white/5 rounded-xl p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="h-8 w-8 rounded-full bg-[#090a0d] flex items-center justify-center border border-white/10">
                      <span className="text-white/60 font-bold">3</span>
                    </div>
                    <h3 className="text-lg font-semibold text-white">What happens after you sign in</h3>
                  </div>
                  <p className="text-sm text-[#8a8f98] mb-4">
                    Once authorized, follow these three steps to go live:
                  </p>
                  <ol className="text-sm text-[#8a8f98] space-y-3">
                    <li className="flex items-start gap-3">
                      <span className="h-5 w-5 rounded-full bg-[#ccff00]/10 border border-[#ccff00]/30 text-[#ccff00] text-[11px] font-bold flex items-center justify-center flex-shrink-0 mt-0.5">1</span>
                      <span><strong className="text-white">Open Roblox Studio</strong> and install the Apple Juice plugin from the Creator Store.</span>
                    </li>
                    <li className="flex items-start gap-3">
                      <span className="h-5 w-5 rounded-full bg-[#ccff00]/10 border border-[#ccff00]/30 text-[#ccff00] text-[11px] font-bold flex items-center justify-center flex-shrink-0 mt-0.5">2</span>
                      <span><strong className="text-white">Copy your Pairing Token</strong> from the dashboard and paste it into the plugin to link your session.</span>
                    </li>
                    <li className="flex items-start gap-3">
                      <span className="h-5 w-5 rounded-full bg-[#ccff00]/10 border border-[#ccff00]/30 text-[#ccff00] text-[11px] font-bold flex items-center justify-center flex-shrink-0 mt-0.5">3</span>
                      <span><strong className="text-white">Click &ldquo;Fetch Context&rdquo;</strong> in the plugin to sync your Explorer tree. You&apos;re ready to generate.</span>
                    </li>
                  </ol>
                </div>
              </div>
            </div>
            
            {/* Footer */}
            <div className="px-6 py-5 border-t border-white/10 bg-[#16191f] flex flex-col sm:flex-row items-center justify-between gap-4">
              <p className="text-[11px] text-[#8a8f98] text-center sm:text-left">
                Apple Juice is an independent project. Not affiliated with Roblox Corporation.
              </p>
              <div className="flex items-center gap-3">
                <button 
                  onClick={() => setShowAuthGuide(false)}
                  className="px-4 py-2.5 rounded-xl border border-white/10 text-white hover:bg-white/5 text-sm font-medium transition-colors hidden sm:block"
                >
                  Cancel
                </button>
                <button 
                  onClick={() => signIn("google", { callbackUrl: "/dashboard" })}
                  className="px-6 py-2.5 rounded-xl bg-white/5 text-white border border-white/10 hover:bg-white/10 text-sm font-bold transition-colors flex items-center gap-2"
                >
                  <svg viewBox="0 0 24 24" className="w-4 h-4" fill="currentColor">
                    <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/>
                    <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
                    <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/>
                    <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
                  </svg>
                  Google
                </button>
                <button 
                  onClick={() => signIn("roblox", { callbackUrl: "/dashboard" })}
                  className="px-6 py-2.5 rounded-xl bg-white text-black hover:bg-zinc-200 text-sm font-bold transition-colors"
                >
                  Roblox
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
