import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

export const IdeMockup = () => {
  const [lines, setLines] = useState(0);
  const [errorFixed, setErrorFixed] = useState(false);
  
  useEffect(() => {
    const timer1 = setInterval(() => {
      setLines(l => (l < 15 ? l + 1 : l));
    }, 400);
    
    const timer2 = setTimeout(() => {
      setErrorFixed(true);
    }, 8000);

    return () => { clearInterval(timer1); clearTimeout(timer2); };
  }, []);

  return (
    <div className="ide-wrapper">
      <div className="ide-titlebar">
        <div className="win-dot" style={{background: '#ff5f57'}}></div>
        <div className="win-dot" style={{background: '#febc2e'}}></div>
        <div className="win-dot" style={{background: '#28c840'}}></div>
        <div className="ide-title">Apple Juice — Dashboard</div>
      </div>
      
      <div className="ide-topbar">
        <div className="tab-row">
          <div className="tab active">RoundSystem.server.lua</div>
          <div className="tab">MapVoting.client.lua</div>
        </div>
        <div className="ml-meter">
          <div className="ml-label">Juice</div>
          <div className="ml-bar-wrap"><div className="ml-bar-fill" style={{ width: `${100 - (lines * 2)}%` }}></div></div>
          <div className="ml-text">{2000 - (lines * 10)} mL</div>
        </div>
      </div>

      <div className="ide-body">
        <div className="explorer">
          <div className="explorer-header">Explorer</div>
          <div className="tree-node"><span className="icon ic-service"></span> Workspace</div>
          <div className="tree-node" style={{paddingLeft: 32}}><span className="icon ic-folder"></span> Maps</div>
          <div className="tree-node"><span className="icon ic-service"></span> ReplicatedStorage</div>
          <div className="tree-node" style={{paddingLeft: 32}}><span className="icon ic-folder"></span> SharedModules</div>
          <div className="tree-node" style={{paddingLeft: 32, color: '#a3ff12'}}><span className="icon ic-script" style={{background: '#a3ff12'}}></span> StatusEvent</div>
          <div className="tree-node"><span className="icon ic-service"></span> ServerScriptService</div>
          <div className="tree-node active" style={{paddingLeft: 32}}><span className="icon ic-script"></span> RoundSystem</div>
        </div>

        <div className="editor">
          {lines > 0 && <div className="code-line"><span className="line-num">1</span><span className="line-code"><span className="cm">-- RoundSystem.server.lua (generated by Apple Juice)</span></span></div>}
          {lines > 1 && <div className="code-line"><span className="line-num">2</span><span className="line-code"><span className="kw">local</span> <span className="var">Players</span> = <span className="var">game</span>:<span className="fn">GetService</span>(<span className="str">"Players"</span>)</span></div>}
          {lines > 2 && <div className="code-line"><span className="line-num">3</span><span className="line-code"><span className="kw">local</span> <span className="var">RS</span> = <span className="var">game</span>:<span className="fn">GetService</span>(<span className="str">"ReplicatedStorage"</span>)</span></div>}
          {lines > 3 && <div className="code-line"><span className="line-num">4</span><span className="line-code"></span></div>}
          {lines > 4 && <div className="code-line"><span className="line-num">5</span><span className="line-code"><span className="kw">local function</span> <span className="fn">startRound</span>()</span></div>}
          {lines > 5 && <div className="code-line"><span className="line-num">6</span><span className="line-code">  <span className="fn">assignTeams</span>(<span className="var">Players</span>:<span className="fn">GetPlayers</span>())</span></div>}
          
          {lines > 6 && !errorFixed && <div className="code-line line-error"><span className="line-num">7</span><span className="line-code">  <span className="var">RS</span>.<span className="var">StatusEvent</span>:<span className="fn">FireAllClients</span>(<span className="str">"Round Start!"</span>)</span></div>}
          {lines > 6 && errorFixed && <div className="code-line line-fixed"><span className="line-num">7</span><span className="line-code">  <span className="kw">local</span> <span className="var">event</span> = <span className="var">RS</span>:<span className="fn">FindFirstChild</span>(<span className="str">"StatusEvent"</span>)</span></div>}
          
          {lines > 7 && <div className="code-line"><span className="line-num">8</span><span className="line-code">  <span className="fn">task.wait</span>(<span className="var">ROUND_TIME</span>)</span></div>}
          {lines > 8 && <div className="code-line"><span className="line-num">9</span><span className="line-code"><span className="kw">end</span></span></div>}
        </div>

        <div className="activity">
          <div className="activity-header">Agent Activity</div>
          {lines > 2 && (
            <motion.div initial={{opacity:0, x:10}} animate={{opacity:1, x:0}} className="activity-step">
              <div className="step-icon">✓</div>
              <div><div className="step-label">studio_get_tree</div><div className="step-detail">Read workspace hierarchy</div></div>
            </motion.div>
          )}
          {lines > 5 && (
            <motion.div initial={{opacity:0, x:10}} animate={{opacity:1, x:0}} className="activity-step">
              <div className="step-icon">✓</div>
              <div><div className="step-label">studio_write_script</div><div className="step-detail">RoundSystem.server</div></div>
            </motion.div>
          )}
          {errorFixed && (
             <motion.div initial={{opacity:0, x:10}} animate={{opacity:1, x:0}} className="activity-step">
               <div className="step-icon">✓</div>
               <div><div className="step-label">studio_run_playtest</div><div className="step-detail" style={{color: '#a3ff12'}}>0 errors detected</div></div>
             </motion.div>
          )}
        </div>
      </div>

      <div className="statusbar">
        <span>● Connected to Studio</span>
        <span>Port 4800</span>
        <span>Luau</span>
        <span>{errorFixed ? "Idle" : "Writing RoundSystem.server..."}</span>
      </div>
    </div>
  );
};
